### ISSUE TITLE
Add a link on the FFIEC website to the Update Signup Page

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#1007]
The website https://content.consumerfinance.gov/compliance/compliance-resources/signup/ is public & allows users to signup for updates regarding HMDA data. The HMDA section is not visible yet, but will be soon. Creating a ticket to discuss where we would link to this on the HMDA website.

**Comment by meissadia** [comment]
Unable to build and test deployment on Prod due to Docker errors.  

> 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

Is this an issues with shared service account? My IP? I haven't been building anything today so this is very odd.
