### ISSUE TITLE
Change date of Q2 quarterly filing deadline

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#1080]
Submission of Q2 data will be considered timely if completed by August 30, 2021, not August 31. 

![image](https://user-images.githubusercontent.com/41752348/129979968-4dcd2fc4-3287-447d-baa1-7406fc2fc0aa.png)

**Comment by ericspry** [comment]
Should state, "will be considered timely if completed on or before August 30, 2021."
