### ISSUE TITLE
Save & Share your work feature

### ISSUE THREAD

**Issue by MattPerrine** [cfpb/hmda-frontend#109]
Consider developing an easy way for users to bookmark and share search parameters from DB.
Before implementing we should user test this feature.

![image](https://user-images.githubusercontent.com/25694077/65158648-c9159200-da00-11e9-977b-454b666a57fd.png)

**Comment by meissadia** [comment]
- [Copying text to clipboard](https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript)
- [Bookmark page](https://github.com/jxom/react-bookmark)
