### ISSUE TITLE
Update Documentation and Tools to default to 2021

### ISSUE THREAD

**Issue by PatrickGoRaft** [cfpb/hmda-frontend#1162]
- [ ] [LARFT](https://ffiec.cfpb.gov/tools/lar-formatting) doc link
- [ ] [FFVT](https://ffiec.cfpb.gov/tools/file-format-verification) tool default

**Comment by meissadia** [comment]
- LARFT documentation link already points to 2021
- Year selection for the FFVT tool has been removed, so no change required there
