### ISSUE TITLE
Update website with resubmission guidance

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#1181]
The resubmission window for 2018 ends on 12/31/21 - we should add a note for this on the filing platform

**Comment by meissadia** [comment]
## Filing Homepage
<img width="1071" alt="Screen Shot 2021-11-03 at 12 10 37 PM" src="https://user-images.githubusercontent.com/2592907/140168202-748ff548-9e9c-448d-91ff-959e14e5b0d2.png">

## Logged in to the Filing application
<img width="1068" alt="Screen Shot 2021-11-03 at 12 10 53 PM" src="https://user-images.githubusercontent.com/2592907/140168258-b39d02b2-842d-4e62-9b6d-04c744e6dcff.png">

**Comment by kgudel** [comment]
1. Place at the end of persitent URL.

1. End of year banner message:
   ```
   2018 Resubmissions Ending:

   The resubmission of 2018 HMDa data will be accepted until Dec 31, 2021 link
   ```

**Comment by meissadia** [comment]
@chynnakeys @kgudel 
 
## Banner that will be shown on the Filing homepage
 
<img width="1160" alt="filing-banner" src="https://user-images.githubusercontent.com/2592907/142704957-f800e010-7195-4d1d-9aca-fa95d80674fc.png">

## Documentation page linked by the banner
 
<img width="1211" alt="timeline-docs-page" src="https://user-images.githubusercontent.com/2592907/142705003-96ac836f-5769-45ef-b8a8-27899ca8e181.png">

**Comment by chynnakeys** [comment]
Love the idea of also adding the chart! @meissadia this looks good to me. can the link also be added to the documentation section https://ffiec.cfpb.gov/documentation/2021/?

**Comment by meissadia** [comment]
- [ ] Part 1 - Create supporting documentation
- [ ] Part 2 - Display a Filing banner that links to the supporting documentation
