### ISSUE TITLE
Rate Spread Issue Banner 

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#1195]
Short description explaining the high-level reason for the new issue.

## Current behavior
There is an issue with permissions and the rate spread fixed and adjustable tables are not updated for 11/15 as of 11/12 at 5 pm. 

We should create a banner and update on the rate spread and home page to notify users. 
Language: We are experiencing a delay in processing the latest Fixed and Adjustable Rate Tables. We are working to resolve the issue and will update the 11/15 APOR tables as soon as possible.

**Comment by meissadia** [comment]
Rate Spread updates have been posted.  Homepage banner along with Rate Spread page messaging has been updated in [Ticket 1197](https://github.com/cfpb/hmda-frontend/issues/1197).
