### ISSUE TITLE
Use HEAD call on S3 files to get last modified date

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-frontend#1196]
S3 URLs support the head method to get metadata about the file including the last modified date in the headers of the return. This can be used to easily provide users with information on when our files were lasted updated without increasing the site's maintenance burden.

As an example:

`https://s3.amazonaws.com/cfpb-hmda-public/prod/dynamic-data/dynamic_lar_ultimate_2017.txt` returns:

`Last-Modified: Thu, 13 Feb 2020 18:51:53 GMT`

**Comment by meissadia** [comment]
<img width="1002" alt="Screen Shot 2021-12-13 at 5 22 16 PM" src="https://user-images.githubusercontent.com/2592907/145911553-3d4fe511-c012-4a2a-a827-7a6f918e64e6.png">
