### ISSUE TITLE
Add cypress test for 1m row submission, and notify MM if not successful

### ISSUE THREAD

**Issue by lchen-2101** [cfpb/hmda-frontend#1212]
Schedule this test to run on nightly basis

- [x] Generate 494,099 rows / 511.9MB row test file for Frontend Test Bank
- [x] Confirm test file can be submitted and signed
- [x] Create `Large Filer` Cypress test
- ~Create separate shell script to run `Large Filter` test separately? Create separate image tag?~
- [x] Update Cypress Large Filer testing image
- [x] Verify MM integration on test failure
- [x] Verify MM integration on success
- [x] Resolve v716 in 2022 test file
- [x] Discuss implications of this testing
  - [x] Pushing >1GB of filing data daily, but it's not needed long-term.  Should we automate its cleanup?
- [x] Decouple max-test-file from the test-image?
  - [x] 500MB file is too large to store on Github
  - [x] Store it in S3 and `curl` it in the `docker-runner` script?

**Comment by meissadia** [comment]
Bumping up against a file size limit.  Not sure if it's Node or Cypress or something in-between. Sounds like the limit is 512MB, our 1M row file is > 1GB.

```
cannot create a string longer than 0x1fffffe8 characters
```

Now that I've encountered the error, I feel like we might have run into this in previous attempts to automate.  

Initial web searches don't provide any workaround.  Maybe there's a way to provide Cypress a stream to the fixture file that it can read/forward to the app but this may be a dead-end.

**Comment by meissadia** [comment]
- Large filter test pod is being evicted due to long runtime, need to explore grace-period extension.
- We cannot store the `2020-FRONTENDTESTBANK99999-MAX.txt` file in our repo due to size restrictions.  Need to explore hosting this elsewhere, pulling the file into the load-testing pod at run time, and then testing.

**Comment by meissadia** [comment]
Upgrading infrastructure resolved the pod eviction issues.  Multiple loads tests complete on Beta, one on Prod.

**Comment by meissadia** [comment]
Github Large File Storage - 1GB storage/ 1GB bandwidth
- Not sufficient for our needs
