### ISSUE TITLE
Builds not being tagged on docker hub

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-frontend#1235]
The most recent tag on docker hub is 1.5.1, while the most recent release here is 1.7.2.  Are you planning on pushing the releases to docker hub again?

**Comment by meissadia** [comment]
Hey @jmurphy-asurity, thank you for the gentle reminder.  We have been diligent since v2.0.0 about pushing Frontend releases to Dockerhub and will continue to do so.  Apologies for any inconvenience.
