### ISSUE TITLE
2019 LARFT Release

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-frontend#124]
Update 2018 LAR Formatting Tool for 2019. This will require some minor updates to the notes in the tool to point to the 2019 FIG and update a few codes that are different in 2019. 

I would also strongly suggest 1 enhancement. Current column A should be moved to Column B and we should insert a new column A labeled "LAR File Row" which should correspond to the ACTUAL row in the txt file that gets created. So many users get confused because rows 1, 2 and 4 don't carry over to the txt file and they subsequently can't find parsing errors that are identified by row in the txt file.

**Comment by meissadia** [comment]
@chynnakeys Since we're passed the 2019 filing period, can this be closed?  Does it need to roll over into a 2020 LARFT enhancement?

**Comment by chynnakeys** [comment]
this actually reflects the current design of the LARFT and can be closed.
