### ISSUE TITLE
Dynamic Datasets - Indicate which years are no longer updated

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1256]
Once #1214 is merged, we can utilize the new `config.filingPeriodStatus` to determine which Datasets are still being updated and display an appropriate UI indicator.

**Comment by meissadia** [comment]
## Mockup v2

updated|not update
---|----
<img width="873" alt="updated" src="https://user-images.githubusercontent.com/2592907/146335002-cbc13745-65f1-4ef2-9775-c48507a7cd8c.png">|<img width="889" alt="not-updated" src="https://user-images.githubusercontent.com/2592907/146335053-0d863ada-0ada-40ed-b357-51639542654c.png">

**Comment by meissadia** [comment]
## Mockup v3

updated|not update
---|----
<img width="866" alt="Screen Shot 2021-12-16 at 2 30 17 PM" src="https://user-images.githubusercontent.com/2592907/146452099-54211b6d-7cb6-4e41-9398-dd262ba8d5d3.png">|<img width="829" alt="Screen Shot 2021-12-16 at 2 30 11 PM" src="https://user-images.githubusercontent.com/2592907/146452108-bf224f84-52e5-4f9f-b1cc-c4f5e718c0b9.png">

**Comment by meissadia** [comment]
## Mockup v4
- Uses CFPB icons (refresh, disabled)

updated|not update
---|----
<img width="903" alt="Screen Shot 2021-12-17 at 5 01 05 PM" src="https://user-images.githubusercontent.com/2592907/146620937-5a8700be-6366-4970-8ab1-44a9be88165f.png">|<img width="888" alt="Screen Shot 2021-12-17 at 5 01 12 PM" src="https://user-images.githubusercontent.com/2592907/146620957-429d9217-2720-4a47-836b-679b7d5bd238.png">

**Comment by PatrickGoRaft** [comment]
LGTM.
