### ISSUE TITLE
[Cypress] Include full output in pod logs

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1277]
- `bus` connection error messages are replacing the Cypress test status messages.
- `bus` [errors are safe to ignore](https://github.com/cypress-io/cypress/issues/4925#issuecomment-573576303)
- Need to find a way to display Cypress test status messages (Running the hmda-cypress pod locally, I'm able to see both.  Maybe there's a debug flag to show everything).

**Comment by meissadia** [comment]
After further observation, the appropriate Cypress logs are being displayed at the end of the test runs, despite the `bus` error messages. 
 
Closing this as a non-issue.

**Comment by gargshashank0107** [comment]
The cypress logs are displayed after the error but the execution becomes quite slow due to this error
