### ISSUE TITLE
Include the size of the downloaded dataset prior to downloading data publication products 

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#1315]
It would be helpful if the size of the dataset is shown prior to downloading so I can estimate exactly how large the file is before downloading. It would be also be helpful to have the download available as a txt or flat file to reduce the file time for downloading.

**Comment by meissadia** [comment]
This can be tied into the <S3Docs> component which already does a `HEAD` call on S3 files to determine the last updated date. 
 
[ Make `Content-Length` human-readable](https://stackoverflow.com/a/20732091/15861235)

**Comment by meissadia** [comment]
<img width="803" alt="Screen Shot 2022-03-01 at 11 22 51 AM" src="https://user-images.githubusercontent.com/2592907/156226839-1da9bed7-9fd4-46e5-9209-14b867b569c2.png">
<img width="854" alt="Screen Shot 2022-03-01 at 11 23 25 AM" src="https://user-images.githubusercontent.com/2592907/156226858-71bf59a7-302d-4bf5-b6e4-6d1286f54b12.png">
<img width="955" alt="Screen Shot 2022-03-01 at 11 23 02 AM" src="https://user-images.githubusercontent.com/2592907/156226867-96ab554a-8484-4fb0-a4f3-43335795bdf6.png">

**Comment by meissadia** [comment]
## Large file warning
closed|open
---|---
<img width="1129" alt="closed" src="https://user-images.githubusercontent.com/2592907/156249018-595aa7e0-8699-45f9-ba30-7b892e0a45cb.png">|<img width="1120" alt="open" src="https://user-images.githubusercontent.com/2592907/156249035-5fb37b41-fabb-41f5-9b41-44b55e0cb528.png">

## Simplified labels
<img width="872" alt="three-year-less-labels" src="https://user-images.githubusercontent.com/2592907/156248911-01f963d7-6368-4449-8865-8f270749f780.png">

**Comment by meissadia** [comment]
<img width="882" alt="Screen Shot 2022-03-03 at 10 10 09 AM" src="https://user-images.githubusercontent.com/2592907/156616000-00b125c4-3b31-4c47-b709-276d1ccce583.png">
