### ISSUE TITLE
Defaults for Rate Spread UI

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1318]
Proposed in #1313

Current | New
---|---
<img width="454" alt="Screen Shot 2022-01-24 at 11 10 36 AM" src="https://user-images.githubusercontent.com/2592907/150840020-d6c88509-6eaf-4b94-a1b4-17aa4bb25bae.png">|<img width="454" alt="Screen Shot 2022-01-24 at 11 10 26 AM" src="https://user-images.githubusercontent.com/2592907/150840038-cf194f74-b004-4617-a0fb-375839520857.png">

**Comment by ericspry** [comment]
Let's go forward with the default `rate set date` to current date, but leave APR and loan term as is.
