### ISSUE TITLE
v716 is not showing the edit description

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-frontend#1319]
The edit description is not appearing for v716. Screenshot from a user's Beta platform

![image](https://user-images.githubusercontent.com/58990254/151036041-81ee8cc4-6d3f-4919-89c6-d21c01640eb1.png)

V716 Description:
An invalid Property Location was reported. Please
review the information below and update your file
accordingly:
1) The reported State and County are not a valid
combination. If neither State nor County were
reported NA, then the County must be located within
the State

**Comment by meissadia** [comment]
@audayshankar I'm assuming this is for 2021 but can you please confirm/deny?
 
 I have a [draft PR](https://github.com/cfpb/hmda-platform/pull/4370) to add this missing description for 2021.

**Comment by audayshankar** [comment]
validated in hmda4 that this works

![image](https://user-images.githubusercontent.com/58990254/151247685-97f65ec3-ae39-4bf6-8507-38bdffd55da7.png)
