### ISSUE TITLE
Parser isn't reading LEIs with spaces

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#132]
Short description explaining the high-level reason for the new issue.
Parser isn't reading LEIs with spaces as incorrect. When there is a space in the LEI in the LAR line, the parser doesn't note this as a formatting error. But it notes it in the S/V edits. It should be a parser error. This does however work with ULIs. 

## Current behavior
![image](https://user-images.githubusercontent.com/41752348/71847115-0727e600-30c4-11ea-8909-c4a3e8f0f6c2.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/41752348/71847371-9f25cf80-30c4-11ea-8168-9c14b3539b26.png)

## Steps to replicate behavior (include URLs)

1. File to test: [Bank1_is not NA (lowercase).txt](https://github.com/cfpb/hmda-frontend/files/4027697/Bank1_is.not.NA.lowercase.txt)

**Comment by meissadia** [comment]
The [FFVT](https://ffiec.cfpb.gov/tools/file-format-verification) also considers the format of the provided test file correct, so this may be a validation that needs to be added on the backend.  

The [FFVT](https://ffiec.cfpb.gov/tools/file-format-verification) does not identify a format error when there is a space in the ULI, so it could be using different parsing logic. 

@omnipresent07 @BarakStout @PatrickHSI could you please check if the backend is currently looking for spaces in the LEI and ULI fields of LAR rows during file format verification of a filing submission?  

Observations:
- A space in a LAR LEI uploads without error and does not trigger a parse error but shows up as a syntactical edit.
- A space in a LAR ULI fails during upload with the following status
```json
{
  "code": -1,
  "message":"An error occurred while submitting the data.",
  "description":"Please re-upload your file."
}
```

**Comment by omnipresent07** [comment]
This appears to be a backend issue. Ticket with PR here: https://github.com/cfpb/hmda-platform/pull/3408

**Comment by wpears** [comment]
Closing since this is tracked in cfpb/hmda-platform#3408
