### ISSUE TITLE
[Tools] Online LARFT

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1339]
## Demo
[HMDA Beta - LAR Formatting Tool](https://ffiec.beta.cfpb.gov/tools/lar-formatting)
 
[Latest Documentation](https://github.com/cfpb/hmda-frontend/blob/5083877a1ff0bb4cba9069bdc500e3a11a5cb5a7/src/documentation/markdown/2021/lar-formatting-new.md) (Updated: 2/25/22)

## Motivation
The current LAR Formatting Tool is Excel based and does not work effectively on OSX. 

## Goals
As an MVP, we want to provide a web-based tool to 
- CRUD Rows
- Export a LAR file
- Import a LAR file

## Longterm we'd like to
- Integrate the check-digit calculator
- Integrate the rate spread calculator
- Integrate single-line edit checks
- Integrate full-file edit checks
- Optimize performance for larger LAR files

## Bugs
- `Age` fields need to allow numeric entry, along with the NA/No-co applicant entries in the dropdown
- `Credit score` need to allow numeric input

**Comment by Michaeldremy** [comment]
Implemented fixes for the bugs that appear on this ticket.

- `Age` fields need to allow numeric entry, along with the NA/No-co applicant entries in the dropdown
- `Credit score` need to allow numeric input

**Comment by meissadia** [comment]
Thoughts
- Add progress indicators, similar to the Filing process progress bar, to help users understand which elements/steps are incomplete for their LAR file
  - TS Row exists?
  - At least one LAR row exists?
- Text guidance about what is required in a LAR file
  - Link to FIG + page for each requirement?

**Comment by Michaeldremy** [comment]
> [Bug] After adding/deleting a LAR row, the Transmittal Sheet (column 13) should automatically update to reflect the adjusted LAR row count
 > - This TS field should probably not be user editable since it MUST match the LAR count and we can easily calculate that value.

The above bug has been fixed. 

**VISUAL UPDATE**: Table input visibility has been increased from 6 rows to 10 rows.

**NEW BUG**: Button for `Update Row {id}` does not change to `Save Row` when editing a existing row and changing Column 1 to the opposite record.

_How to replicate:_ create a TS/LAR row save the row then click on a field in that row change `Column 1` to be the opposite row (i.e LAR -> TS or TS -> LAR). Button will continue to say `Update Row {id}` instead of `Save Row`.

Image of bug:
<img width="995" alt="image" src="https://user-images.githubusercontent.com/60801873/196788312-79687f6d-f62b-41f9-ad3f-d9c36485261d.png">

**Comment by Michaeldremy** [comment]
> [Feature] When navigating away from the page, prompt user that they will lose any unsaved data
> - Short term we can always prompt, if there are saved TS or LAR records
> - Long term we should only prompt when there are new changes since the last time the user clicked Download File

Following the second bullet point the feature has now been implemented.

> [Feature] Name the downloaded file based on the TS data: ${year}-${quarter}-${lei}.txt

Feature has been implemented.

**Comment by meissadia** [comment]
> Implemented fixes for the bugs that appear on this ticket.
> 
> * `Age` fields need to allow numeric entry, along with the NA/No-co applicant entries in the dropdown
> * `Credit score` need to allow numeric input

## Issue
The `Credit score` drop-downs are defaulting to `Credit score is not a number` even when a Credit Score that is not `7777` is entered into the input field.  

1) This could be confusing to users 
2) If a user wanted to use the drop-down to actually set the field value as `Credit score is not a number` they would need to use the drop-down to select another enumeration and then switch back to `Credit score is not a number`
 
 ## Screenshot
 <img width="979" alt="Screen Shot 2022-10-21 at 11 43 37 AM" src="https://user-images.githubusercontent.com/2592907/197258339-3c39ecb9-87ae-47e2-8f43-fcd970b818e2.png">

## Thought
When the input value does not match one of the enumerations, the drop-down should display something else like `Credit Score` or `Other`.

**Comment by Michaeldremy** [comment]
> > Implemented fixes for the bugs that appear on this ticket.
> > 
> > * `Age` fields need to allow numeric entry, along with the NA/No-co applicant entries in the dropdown
> > * `Credit score` need to allow numeric input
> 
> ## Issue
> The `Credit score` drop-downs are defaulting to `Credit score is not a number` even when a Credit Score that is not `7777` is entered into the input field.
> 
> 1. This could be confusing to users
> 2. If a user wanted to use the drop-down to actually set the field value as `Credit score is not a number` they would need to use the drop-down to select another enumeration and then switch back to `Credit score is not a number`
> 
> ## Screenshot
> <img alt="Screen Shot 2022-10-21 at 11 43 37 AM" width="979" src="https://user-images.githubusercontent.com/2592907/197258339-3c39ecb9-87ae-47e2-8f43-fcd970b818e2.png">
> 
> ## Thought
> When the input value does not match one of the enumerations, the drop-down should display something else like `Credit Score` or `Other`.

## Issue has been fixed

User will now see an option called `Other` which gets defaulted if the user doesn't select from the other three options or inputs their own input.

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/60801873/197302743-b5808393-462d-4673-99e1-1100f1931b89.png">

**Comment by Michaeldremy** [comment]
### New feature added

An icon with a tooltip explaining the disabled input will now display on specific disabled input fields. Schema has been updated to handle tooltips.

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/60801873/197302995-b5225e71-affa-47ca-bcc0-d72d94d49880.png">

### Additonally

After discussing with Meissa we determined to disable `Column 1` and let the tool automatically update to a new record. This will make for a smoother user experience. 

<img width="993" alt="image" src="https://user-images.githubusercontent.com/60801873/197303225-5b79faa7-9cac-40c0-8229-8582aca82fe2.png">


The below bug is the final bug that needs to be fixed. Fixing this bug is crucial as it serves the above comment/image.

> [Bug] After creating and saving a TS, the Creation section should default to creating a LAR row (since only one TS per file)
> - I think feature is something already implemented but just has a bug
> - Clicking the Clear button does correctly begin the creation of a LAR row, if a saved TS row exists, but that is not an intuitive way to start the LAR creation process

**Comment by chynnakeys** [comment]
@Michaeldremy @meissadia can we remove the "The HMDA LAR" section? It seems repetitive 
![image](https://user-images.githubusercontent.com/41752348/198351912-776b04f1-ca92-48ff-ab36-460b1136caa6.png)

Also, can we add the 2023 year to the dropdown for year, since the 2023 beta is now available?

**Comment by Michaeldremy** [comment]
> Can we remove the "The HMDA LAR" section? It seems repetitive ![image](https://user-images.githubusercontent.com/41752348/198351912-776b04f1-ca92-48ff-ab36-460b1136caa6.png)
> 
> Also, can we add the 2023 year to the dropdown for year, since the 2023 beta is now available?

Changes have been made!

**Comment by meissadia** [comment]
Items I'll work on
- Change `Clear` button to `New Row` 
  - Makes it clearer how to start a new row
- Change `Clear Saved` to `Clear All`? `Reset`? `Start Over`? 
  - Make it clearer that this also wipes out any records in-progress
  - I think I like `Reset` best
- Field details
  - Remove arrows (visual clutter)
  - Move bottom spacing to the top
  - <img width="587" alt="Screen Shot 2022-11-17 at 11 25 51 AM" src="https://user-images.githubusercontent.com/2592907/202527817-791adc7c-fe12-4559-baa9-a3b7ae18175a.png">
- Lighten tooltip icon, more grey
  - <img width="966" alt="Screen Shot 2022-11-17 at 11 27 41 AM" src="https://user-images.githubusercontent.com/2592907/202528121-a28fb322-56a6-4228-9739-49f41d09455d.png">
- Fix awkward text-wrapping in button
  -  <img width="986" alt="Screen Shot 2022-11-17 at 9 59 11 AM" src="https://user-images.githubusercontent.com/2592907/202528969-a1484b9e-6267-4409-be62-e1dfacaa9224.png">
- Add horizontal divider between `file actions` toolbar and the `Saved Records` section

**Comment by meissadia** [comment]
Remaining issues:
- [ ] Parsed column not being highlighted even though it's selected
- [ ] Saved LAR: Awkward sizing of 1st column when searching/filtering (too narrow to see full column content for longer ones, like ULI)
- [ ] Feature: Numeric inputs should only allow numbers
- [ ] Bug: Saved TS - Search then clear search, scroll right, some column headers are missing the background color

**Comment by meissadia** [comment]
Pending
- [ ] Test relocated schema generator
- [ ] Documentation
  - [ ] Add link to documentation on LARFT page?
  - [x] Update documentation for all years
  - [x] fix formatting
  - [x] Update images
- [ ] Unify between Prod/Beta
  - src/homepage/ForFilers/Filing.jsx
- [ ] Next Release
  - [ ] Bug: [Table columns mis-aligned after clearing search/filter ](https://github.com/cfpb/hmda-frontend/issues/1681)
  - [ ] Feature: Numeric inputs should only allow numbers (add fieldType in schema)    
  - [ ] Split css by component/feature
    - src/tools/larft/index.css

**Comment by meissadia** [comment]
Other ideas for expansion coming out of quarterly planning:
- [ ] Integrate the FFVT into the OLARFT? 
  - Uploaded files could be passed to FFVT endpoint prior to the OLARFT parsing rows. The API provides the row number and ULI of problematic rows. Then for identified issues:
    - Option: Present a separate editor for rows with FFVT issues?
    - Option: Display an icon (w/ message onClick) to explain FFVT identified issue for problematic rows
