### ISSUE TITLE
[HMDA Help] Include LEI in the URL to allow direct linking

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1354]
This would make it easier to share links to Institutions, instead of other user having to go to HMDA Help, search, select the appropriate institution for the appropriate year [include the year in the URL too, if not there].

**Comment by Michaeldremy** [comment]
11.10.2022 Updates:

- `/search/lei/:id` supports direct linking to an institution enabling folks to allow the ability to send specific institutions to one another and or save the url to a bookmark.
- `/update/lei/:year/:id` supports direct linking to a institutions specific year where folks can update as before. Helps sending links easier.

Bugs to work on:
- When doing a direct link to the `/search` route the drop-down for production data does not show the institution that is from the url and the drop-down is still forced open
  - Ideally the drop-down should be closed and the default value for the drop-down should be the one from the url
- When visiting the `/update` route, making an edit and saving the change an error on the frontend is displayed saying `error.then` is not a function. The data on the back-end is still saved and the changes are made as per usual.
  - Only tested on local data specifically `FRONTENDTESTBANK999` data. We don't want to update any institutions' live data

**Comment by Michaeldremy** [comment]
11.14.2022

> When visiting the /update route, making an edit and saving the change an error on the frontend is displayed saying error.then is not a function. The data on the back-end is still saved and the changes are made as per usual.
Only tested on local data specifically FRONTENDTESTBANK999 data. We don't want to update any institutions' live data

Bug has been fixed.
