### ISSUE TITLE
HMDA Beta Not Displaying Edits Immediately

### ISSUE THREAD

**Issue by sthomas93** [cfpb/hmda-frontend#1425]
![image](https://user-images.githubusercontent.com/99903050/165785857-979ac1c1-dd9a-4bc6-8018-83d95d3d7b90.png)

When a file is uploading it only says that edits are pending. After refreshing the page or logging out and back in it shows that the edits are ready (screenshot below). Fix needed to automatically push beta upload process to edit stage. 

![image](https://user-images.githubusercontent.com/99903050/165786130-fdfb740b-9d18-4cc7-ad2c-4a9e88a17b1c.png)

**Comment by meissadia** [comment]
@sthomas93  I've redeployed the standard (non-websocket) version of the Filing progress bar to Prod-Beta, which should provide a smoother experience for end users.  This eliminates the edit-by-edit bars in favor of the single progress bar.
<img width="1904" alt="Screen Shot 2022-05-05 at 3 37 59 PM" src="https://user-images.githubusercontent.com/2592907/167034366-061d02ce-119a-45b2-ba14-a4898f930bbc.png">
