### ISSUE TITLE
Included New Working with HMDA Data Documentation from CF.gov

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-frontend#1459]
The Documentation can be found here: https://files.consumerfinance.gov/f/documents/cfpb_beginners-guide-accessing-using-hmda-data_guide_2022-06.pdf

**Comment by audayshankar** [comment]
Hallie updated the document with the updated Data Publication landing page screenshot. Are there any other updates we'd like to make?

- Replace the Snapshot National Loan Level Screenshot to display the page showing 2021
- Add any additional detail about our additional data products

### Files
[Beginner's Guide to Accessing and Using HMDA Data_7.6.22 updated screenshot.docx](https://github.com/cfpb/hmda-frontend/files/9067073/Beginner.s.Guide.to.Accessing.and.Using.HMDA.Data_7.6.22.updated.screenshot.docx)
[Beginner's Guide to Accessing and Using HMDA Data_7.6.22 updated screenshot.pdf](https://github.com/cfpb/hmda-frontend/files/9067076/Beginner.s.Guide.to.Accessing.and.Using.HMDA.Data_7.6.22.updated.screenshot.pdf)

**Comment by Kibrael** [comment]
Maybe share it on [Wikipedia](https://en.wikipedia.org/wiki/Home_Mortgage_Disclosure_Act)?
