### ISSUE TITLE
Homepage Reorg

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1485]
Reorganize homepage to help users find what they're looking for more easily.
- [x] Link to API documentation in homepage reorg
- [ ] Automate removal of "New" icons?
- [ ] Naming: Data Publication -> Published Data?
- [ ] One/Three Year - Clarify what the names mean, that they only include 1 year of data each.  
  - [ ] One Year Vintage / One Year Frozen / One Year Aged
- [x] Consolidate Documentation/FAQs
- [x] Split info into focused columns by user type: Filers / Data Users
- [x] Enable sections to be collapsed to allow users to focus on their interests
- [x] Persist user's expanded/collapsed selections via LocalStorage
- [x] Add `New` label to call out recently added points of interest
- [x] Move `Updates and Notes` to more accessible location

![redesign-v3](https://user-images.githubusercontent.com/2592907/184996476-7cb6dd31-c45f-4ef8-8530-ef10a2e88673.png)

**Comment by kgudel** [comment]
Consider putting a `new` tag next to maps on the reorganized homepage.

**Comment by meissadia** [comment]
## User Feedback

Homepage
  - [x] "Institutions" misspelled 
  - Useful to see all of the collapsable sections expanded by default
    - Going forward: Look into Google Analytics to determine how often users collapse/expand sections?
  - Liked the Filers/Data Users split

**Comment by meissadia** [comment]
Combined with Graphs on branch `graphs-homepage-combine`
