### ISSUE TITLE
Decouple Documentation from Years Where Not Necessary

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-frontend#1486]
Short description explaining the high-level reason for the new issue.

## Current behavior

All of the Documentation on the Documentation page is divided into years, even when there is no difference, or no substantial difference between the pieces of documentation.

## Expected behavior

Only use year select for documentation with substantive differences between years.

The only documentation that seems to fall into this category are the FIGs and Supplemental Quarterly Guides.

**Comment by Michaeldremy** [comment]
Documentation has been consolidated and there is no need to reduplicate docs across current/future years anymore. Previously documents would be regenerated each year and would make yearly specific changes to the respective documents.

The updated documentation lives in Docusaurus. To see updated docs in the UI visit beta site [here](https://ffiec.beta.cfpb.gov/documentation/faq/data-browser-graphs-faq).
