### ISSUE TITLE
[Meta] Quarterly Data Visualization Post Release Improvements

### ISSUE THREAD

**Issue by Michaeldremy** [cfpb/hmda-frontend#1510]
- [x] #1532
  - Conforming / Non-conforming -> What do they mean?
  - FHA etc -> What do they stand for?
- [ ] Redesign of FAQ page similar design as ticket 
  - #1487 
  - #1620 
- [x] #1531
- [x] #1530
- [x] #1528
- [x] #1529
- [x] Update language for Data Browser on the Homepage (Fixed in https://github.com/cfpb/hmda-frontend/pull/1515)
  - Current Language: "A suite of tools that allows financial institutions to filter, summarize, download, and visualize HMDA datasets."
  - Desire Language "A suite of tools that allows users to filter, summarize, download, and visualize HMDA datasets."

**Comment by meissadia** [comment]
I'm going to go ahead and close this one.  We've spawned the necessary follow-up tickets and even _those_ tickets are now giving rise to their own offspring, so this ticket has served it's purpose.
