### ISSUE TITLE
Graphs & Homepage Verbiages

### ISSUE THREAD

**Issue by lchen-2101** [cfpb/hmda-frontend#1516]
- [x] Home page
  - [x] typo in `Access the HMDA Filing Platform` (instiutions)
  - [x] `HMDA Data Browser` (A suite of tools that allows financial institutions to..)
  - [x] `HMDA Updates and Notes` change to `HMDA's ...`, also add "NEW" icon
- [x] Quarterly Graphs - `The following graphs represent data for the xyz financial institutions reporting HMDA quarterly data in the current year. The graphs display current quarters and three years of historical data.​` (config changes)
- [ ] Three Year National Loan Level Dataset - The description is causing some confusion. Suggest changing to: ​

  The data includes the Loan Application Register (LAR) and Transmittal Sheet (TS) submitted to the Bureau, which are made available to the public and include adjustments to the data incorporated in the 34 months following the reporting deadline. _Each dataset contains the selected filing year's data with any updates submitted until the year was closed for resubmission​_

  Transmittal sheets include information about the filing institution, reporting period, and contact information. LARs include all data fields relating to the reported loan or application. Each covered loan or application appears on its own line.​

**Comment by Michaeldremy** [comment]
Homepage changes were taken care of on Wednesday.

**Comment by meissadia** [comment]
Re: Quarterly Graphs language.  The extrapolation warning is being removed as part of #1514

**Comment by meissadia** [comment]
Moved the Three Year language update to Issue #1518 since that will not be complete prior to Graphs go live.
