### ISSUE TITLE
Add upper and lower bins to Applicant Age and Co-Applicant Age

### ISSUE THREAD

**Issue by MattPerrine** [cfpb/hmda-frontend#152]
The [Public HMDA data fields with values and definitions page](https://ffiec.cfpb.gov/documentation/2019/lar-data-fields/) was missing the upper and lower bins for applicant age and co-applicant age.

**Comment by MattPerrine** [comment]
After talking with Chynna, we're not going to make this update. technically  >25 and <74 are not binned ages.

**Comment by ericspry** [comment]
minor correction it's <25 and >74 are not binned. Actual ages are reported.
