### ISSUE TITLE
[Graphs] Update Cypress Tests

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1529]
During early development of Quarterly Graphs we had implemented some basic Cypress tests but as our pace and complexity increased we fell behind with keeping them up to date. 
 
https://github.com/cfpb/hmda-frontend/blob/master/cypress/integration/data-browser/graphs.spec.js

**Comment by Michaeldremy** [comment]
When #1553 has been completed and merged. 

Test coverage for user interaction with tabs on the graph page need to have the test urls updated to the finalize urls from the above ticket.

**Comment by Michaeldremy** [comment]
The two tests that relied on filer url has been updated to correctly point to the finalized filer url.
