### ISSUE TITLE
[Graphs] Clarify graph legend terms

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1532]
Provide more detail for acronyms and uncommon terms used in identifying series lines. 
 
Ideally this would be on the Graphs page to avoid requiring extra navigation but, as a first step, inclusion in the Graphs FAQ or separate documentation page might work. 

- HELOC
- FHA
- VA
- RHS/FSA
- Conventional Conforming
- Conventional Non-Conforming

**Comment by Michaeldremy** [comment]
Terms are all on CFPB website except FSA loan. I am unable to locate information on FSA.

Here are the links to the different loan types.

[Conventional Conforming](https://www.consumerfinance.gov/owning-a-home/loan-options/conventional-loans/)

[Non-conforming](https://www.consumerfinance.gov/owning-a-home/loan-options/conventional-loans/) scroll down further to see.

[FHA](https://www.consumerfinance.gov/owning-a-home/loan-options/fha-loans/)

[HELOC](https://www.consumerfinance.gov/ask-cfpb/what-is-a-home-equity-loan-en-106/)

[RSA](https://www.consumerfinance.gov/ask-cfpb/what-is-a-usda-rural-housing-service-loan-en-114/)

Can't find information on FSA loans.

[VA](https://www.consumerfinance.gov/ask-cfpb/what-is-a-va-loan-en-113/)

**Comment by kgudel** [comment]
Here is the main page for the USDA's Farm Service Agency: https://www.fsa.usda.gov/

And for the Farm Loan Program: https://www.fsa.usda.gov/programs-and-services/farm-loan-programs/index
