### ISSUE TITLE
Supplemental Guides are linking to the wrong document

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#1549]
Short description explaining the high-level reason for the new issue.

## Current behavior
The Supplemental Quarterly Guides listed here: https://ffiec.cfpb.gov/documentation/2022/fig/ and here: https://ffiec.cfpb.gov/documentation/2021/fig/ are linking to the wrong guide (2020)
## Steps to replicate behavior (include URLs)

1.

**Comment by kgudel** [comment]
Correct links:

https://s3.amazonaws.com/cfpb-hmda-public/prod/help/supplemental-guide-for-quarterly-filers-for-2021.pdf

https://s3.amazonaws.com/cfpb-hmda-public/prod/help/supplemental-guide-for-quarterly-filers-for-2022.pdf

**Comment by meissadia** [comment]
@Michaeldremy  `src > documentation > FigLinks.jsx > const links`
