### ISSUE TITLE
Update Public Panel - Data Fields: Assets

### ISSUE THREAD

**Issue by sthomas93** [cfpb/hmda-frontend#1554]
Currently "Assets" does not have a clear definition of the field. The description should include the following language:

"The count of assets of the institution in the 4th quarter of the HMDA collection year"

https://ffiec.cfpb.gov/documentation/2022/panel-data-fields/

![image](https://user-images.githubusercontent.com/99903050/190218511-8a362a72-697e-477b-b387-1f0f9521dd86.png)

**Comment by Michaeldremy** [comment]
Does this update need to be reflected in every years documentation or specifically 2022?
