### ISSUE TITLE
Update 2021/2022 LAR Data fields With Removal of Aplicant_age 

### ISSUE THREAD

**Issue by offoaro** [cfpb/hmda-frontend#1592]
Hello,

A recent user noticed two separate identifiers for applicant ages in the LAR Data fields. I am requesting this field below-

https://ffiec.cfpb.gov/documentation/2021/lar-data-fields/#applicant_age

to be removed as it not specific as the duplicate section that details more variables (One shows the binned ages & 8888, the other doesn’t). See below 
 
https://ffiec.cfpb.gov/documentation/2021/lar-data-fields/#ageapplicant

Ageapplicant is the one we want to keep.

**Comment by chynnakeys** [comment]
I would like to also request that [co-applicant age](https://ffiec.cfpb.gov/documentation/2021/lar-data-fields/#co-applicant_age) be updated to 

Description: The age of the co-applicant
Values:
<25
25-34
35-44
45-54
55-64
65-74
>74
8888
9999

**Comment by Michaeldremy** [comment]
@chynnakeys 

Do you want me to add the update you brought forward in addition to the original ticket to every year or specifically 2021/2022?

**Comment by chynnakeys** [comment]
@Michaeldremy 
<25
25-34
35-44
45-54
55-64
65-74
> 74
8888
9999
