### ISSUE TITLE
Update Documentation and Tools to default to 2022

### ISSUE THREAD

**Issue by PatrickGoRaft** [cfpb/hmda-frontend#1648]
- [x] [LARFT](https://ffiec.cfpb.gov/tools/lar-formatting) doc link
- [x] [FFVT](https://ffiec.cfpb.gov/tools/file-format-verification) tool default

**Comment by meissadia** [comment]
- FFVT no longer has a year selector
- LARFT doc link is automatically updated based on the currently open Filing period and already points to 2022 documentation.  Additionally, this will be replaced by the online LARFT soon.
