### ISSUE TITLE
Explore React v18

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1656]
Instructions
https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

Things to watch out for:
Event batching - https://github.com/reactwg/react-18/discussions/21
Updates to strict mode - https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode
No IE support - https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#dropping-support-for-internet-explorer
Other breaking changes - https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#other-breaking-changes

**Comment by Michaeldremy** [comment]
Closing ticket as V3 on the frontend contains React 18 upgrade.
