### ISSUE TITLE
link to go homepage from filing page

### ISSUE THREAD

**Issue by zencircle** [cfpb/hmda-frontend#168]
Short description explaining the high-level reason for the new issue.

## Current behavior
![image](https://user-images.githubusercontent.com/25303681/72554183-2d8a1600-3868-11ea-9940-350a8fe462f9.png)

## Expected behavior
Create link to go back to the main page
![image](https://user-images.githubusercontent.com/25303681/72554255-4b577b00-3868-11ea-9a6e-f8af4359beff.png)

## Steps to replicate behavior (include URLs)

1.

**Comment by wpears** [comment]
This is done
