### ISSUE TITLE
Homepage Improvements

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1702]
- Beta Banner
  - [ ] Differentiate between Beta banner and announcements
    <img width="1078" alt="beta-banner" src="https://user-images.githubusercontent.com/2592907/211121254-06cc3c35-435c-486c-9783-f03797e9a76c.png">

- Announcement Carousel 
  - [ ] Address overflow of longer messages
    <img width="1003" alt="overflow" src="https://user-images.githubusercontent.com/2592907/211121308-953bb8cb-6c89-4cea-b7d8-b150e4d8cd7b.png">

  - [ ] Reduce empty space for shorter messages

**Comment by meissadia** [comment]
Proposed Beta Banner

<img width="1087" alt="beta-banner-new" src="https://user-images.githubusercontent.com/2592907/211121451-3e216ea3-ce92-4730-8ff2-c838e4a54bb5.png">

**Comment by meissadia** [comment]
Alerts: Reduced empty space
|Before|After|
|---|---|
|<img width="1003" alt="Screen Shot 2023-01-06 at 5 22 16 PM" src="https://user-images.githubusercontent.com/2592907/211121669-276ee495-5f9f-40ed-bb9d-c6254da2072a.png">|<img width="1002" alt="Screen Shot 2023-01-06 at 5 22 29 PM" src="https://user-images.githubusercontent.com/2592907/211121684-f088fd13-fb51-4d65-b578-ff2dc0d44a72.png">|

**Comment by zencircle** [comment]
LGTM
