### ISSUE TITLE
[Graphs] Filer Info table incorrectly displaying data

### ISSUE THREAD

**Issue by Michaeldremy** [cfpb/hmda-frontend#1711]
`Filers Info` tab found in [Graphs](https://ffiec.cfpb.gov/data-browser/graphs/quarterly/info/filers) is showing up blank data for 2023. 

### Issue: 

Table is attempting to display 2023 data but that data is not in the API response and can't be calculated since the 2023 filer data has not been finalized.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/60801873/214380597-1cb51325-9e52-4f77-901c-16f61bfa019c.png">

**Comment by meissadia** [comment]
Deployed a temporary fix that hardcodes the `year` variable to `2022`. 

Next steps:
 - Make the year that drives this table part of environment config
