### ISSUE TITLE
Sync Node version across Frontend projects

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1729]
Current versions:
- Frontend: 14.18.3-alpine3.15
- Documentation: 16.14
- Dashboard: 14.17.6-alpine3.11

Options:
- Update all projects to use, at least, the same major version to avoid needing to switch between them during development
- Add a `.nvmrc` file to each project so that we could just `nvm use` to quickly switch to a compatible node version.

Things to keep in mind:
- We strive to use [alpine](https://www.alpinelinux.org/about/) based images as they are designed to be small and secure
- I think `alpine3.15` is our current security standard.  I see [alpine3.16](https://hub.docker.com/_/node) available but we'd need to check with the Ops team if we can use the latest.

**Comment by Michaeldremy** [comment]
Closing ticket as work has been completed.

- Sync Frontend Code formatting #1440 
- `.nvmrc` file was added to the frontend a while back
- Frontend is running on `alpine3.17`
