### ISSUE TITLE
Direct frontend documentation URLs to point to Docusaurus

### ISSUE THREAD

**Issue by Michaeldremy** [cfpb/hmda-frontend#1735]
Routing between HMDA Frontend and Docusaurus

- [x] Update old documentation urls in FE to point to routes found in Docusaurus
- [x] Update markdown files that point to old documentation urls and point to routes found in Docusaurus
   - Branch created for when Docusaurus domain has been launched under the `ffiec.cfpv.gov` domain. Click [here](https://github.com/cfpb/hmda-combined-documentation/tree/prod-markdown-url-updates) to view the branch.
- [x] Update Cypress tests that point to old urls and point to routes in Docusaurus
   - No updates to make
- [x] Setup redirects in Docusaurus to handle old routes that were bookmarked and or are the most common routes via GA - using this [DS plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects)
- [x] Make `404 Not Found` page in Docusaurus more appealing.

> - Once a user is within the scope of React Router (Frontend) how can we route them to Docusaurus without opening the docs page a new window?
> - Ex. Going directly to /documentation/ => Docusaurus. Clicking a link to /documentation/ from within Frontend => Frontend docs
> - Probably just replacing with ? Also removing Frontend's /documentation routes.

**Comment by Michaeldremy** [comment]
Discovering a way to redirect users from frontend to Docusaurus. Issue seems to be when a dynamic route is injected into the url that Ambassador gives the route to Docusaurus to handle. Anything with `/documentation/*` is getting handled by Docusaurus.

Routes correctly redirecting:

- `/documentation`

Routes not working:

- `/documentation/:year`
- `/documentation/:year/:collection`
- `/documentation/:year/:collection/:slug`

**Comment by Michaeldremy** [comment]
Section has been deleted, as modified LAR header documents are no longer needed.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/60801873/224113197-e1b81260-e27f-4783-8c4a-971cba8101a7.png">

**Comment by Michaeldremy** [comment]
https://ffiec.cfpb.gov/documentation/2018/fig/

The above url is a snapshot / isolated view of information related to the FIG found on the homepage.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/60801873/224124541-2ad6936b-feb7-4acf-82b1-08c54c22894b.png">

Issue:
URL will no longer work as any routes that exceed `/documentation/*` are handled by Docusaurus. The current document in the above screenshot has been isolated and is found [here](https://ffiec.beta.cfpb.gov/documentation/faq/data-collection-timelines#annual-filing-period-dates), it contains all the yearly FIG downloadable pdfs. 

On [2018](https://ffiec.cfpb.gov/documentation/2018/fig/) specifically the second link.
<img width="486" alt="image" src="https://user-images.githubusercontent.com/60801873/224125285-3cd207c1-7e88-470e-843f-09c4910760b9.png">

This [file](https://s3.amazonaws.com/cfpb-hmda-public/prod/help/2018-hmda-fig-2018-hmda-rule.pdf) would need to be added to the above mentioned consolidated document.

**Comment by audayshankar** [comment]
In response to the above comment: Link 2 titled `For data collected in 2018 incorporating the 2018 HMDA rule` is the most current 2018 FIG and Link 1 that just says `For data collected in 2018` is outdated. 

It would be best to include Link 2 in the [nice FIG table](https://ffiec.beta.cfpb.gov/documentation/faq/data-collection-timelines#filing-instructions-guide-fig) instead of Link 1 and add a separate footnote to that section referencing Link 1 and indicating it's an older version of the FIG.

Although we are no longer collecting 2018 data, we still need to ensure they are both available even though one is outdated.

**Comment by Michaeldremy** [comment]
> In response to the above comment: Link 2 titled `For data collected in 2018 incorporating the 2018 HMDA rule` is the most current 2018 FIG and Link 1 that just says `For data collected in 2018` is outdated.
> 
> It would be best to include Link 2 in the [nice FIG table](https://ffiec.beta.cfpb.gov/documentation/faq/data-collection-timelines#filing-instructions-guide-fig) instead of Link 1 and add a separate footnote to that section referencing Link 1 and indicating it's an older version of the FIG.
> 
> Although we are no longer collecting 2018 data, we still need to ensure they are both available even though one is outdated.

Has been updated with the above verbiage ✅ 

<img width="974" alt="image" src="https://user-images.githubusercontent.com/60801873/225396813-c5d9d23c-2fc0-4403-8afb-5bca0e70d5b9.png">
