### ISSUE TITLE
[Cypress] Create Combined MLAR tests

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1754]
Tests should validate that:
- the Combined MLAR UI is visible for the released years
- that the file links are valid

In our Cypress tests for the frontend, there are (at least) two places where the file size of files on s3 aren't being read correctly...

It displays correctly in production: https://ffiec.cfpb.gov/data-publication/snapshot-national-loan-level-dataset/2021
But the file sizes show "0B" in Cypress tests (screenshot):
<img width="430" alt="dataset-snapshot" src="https://user-images.githubusercontent.com/3650300/229881803-4bcff48e-4a14-4ec3-9c12-86ce84b7e460.png">

The same is true for the Combined mLAR files...

It displays correctly in production: https://ffiec.cfpb.gov/data-publication/modified-lar/2022
But it is missing in Cypress tests (screenshot)
<img width="560" alt="combined-mlar-missing" src="https://user-images.githubusercontent.com/3650300/229881870-49586b54-88b1-45b9-a3dd-406302053e07.png">

**Comment by ojbravo** [comment]
Added Cypress Test for Combined MLAR. Only checking to see if the files exist on S3 as Cypress blocks the Content-Length from the Response Headers, so the UI doesn't fully show up in Cypress (and thus can't be tested)
