### ISSUE TITLE
[Documentation] Add banner to documentation page

### ISSUE THREAD

**Issue by Michaeldremy** [cfpb/hmda-frontend#1775]
Banner will be displayed on `/documentation` homepage to discuss documentation overhaul.

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/60801873/232862496-2d2b4f9d-0dbb-4c48-b980-bf98e4b6c3fd.png">

**Comment by mmahmood4444** [comment]
I suggest adding "the" before "current documentation" in the second sentence.
