### ISSUE TITLE
Banner for Docusaurus Launch

### ISSUE THREAD

**Issue by mmahmood4444** [cfpb/hmda-frontend#1790]
New and enhanced HMDA documentation page has been released! In addition to an improved visual design, financial institutions now have the ability to search the consolidated documentation and API documentation has been integrated.

[Visit the Redesigned Page](https://ffiec.cfpb.gov/documentation/2023/)

**Comment by audayshankar** [comment]
I added some revisions:

A new and enhanced HMDA documentation page has been released! In addition to an improved visual design, financial institutions now have the ability to search the consolidated documentation and API documentation has been integrated. Visit the [redesigned page.](https://ffiec.cfpb.gov/documentation/2023/)
