### ISSUE TITLE
Update Quarterly Filing Dates in Docs

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-frontend#1795]
Quarterly filing dates are different each year, so we need to reflect that in the documentation: https://ffiec.cfpb.gov/documentation/faq/data-collection-timelines#quarterly-filing-period-dates

Will provide updated dates

The supplemental guide link is also incorrect in the documentation page. Correct link for 2023 filing: https://s3.amazonaws.com/cfpb-hmda-public/prod/help/supplemental-guide-for-quarterly-filers-for-2023.pdf

**Comment by Michaeldremy** [comment]
### Found a few more incorrect filing dates that need to be addressed.

Documentation source URL: https://ffiec.cfpb.gov/documentation/faq/data-collection-timelines#quarterly-filing-period-dates

Image for `Quarterly filing` needs to be updated, it contains wrong dates.

![image](https://github.com/cfpb/hmda-frontend/assets/60801873/2de112c8-9766-4463-82f9-53130e950fb7)

Written out dates are also wrong.

<img width="782" alt="image" src="https://github.com/cfpb/hmda-frontend/assets/60801873/4c047e17-a193-486a-912d-cc080fb5ce96">

**Comment by Michaeldremy** [comment]
Updates have been added and has been deployed to production ✅ 

https://ffiec.cfpb.gov/documentation/faq/data-collection-timelines#quarterly-filing-period-dates

<img width="987" alt="image" src="https://github.com/cfpb/hmda-frontend/assets/60801873/5be40435-a1ac-4278-91fb-57f9f6752f3a">
