### ISSUE TITLE
Redirect links to fix

### ISSUE THREAD

**Issue by Michaeldremy** [cfpb/hmda-frontend#1805]
Ticket created to track any redirect links that need to be fixed.

**Comment by ojbravo** [comment]
<img width="435" alt="check-digit" src="https://github.com/cfpb/hmda-frontend/assets/3650300/7c156eb6-82ef-462f-b11c-d38b3c5da8be">
 Link should point to https://ffiec.cfpb.gov/documentation/api/check-digit/#batch-check-digit-generation and open in a new tab.

**Comment by Michaeldremy** [comment]
<img width="448" alt="image" src="https://github.com/cfpb/hmda-frontend/assets/60801873/48e6feab-a7a2-4927-964a-24fcc0073a69">

Rates spread tool page (https://ffiec.cfpb.gov/tools/rate-spread)
Link has been updated to point to Docusaurus.
