### ISSUE TITLE
[Docusaurus] Error in API Docs

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-frontend#1824]
Data Browser API supports 2018, 2019, 2020, 2021. It will soon support 2022 after 2022 data publication is released. 

Documentation only lists 2018 & 2019.
https://ffiec.cfpb.gov/documentation/api/data-browser/#hmda-data-filters
<img width="368" alt="image" src="https://github.com/cfpb/hmda-frontend/assets/58990254/88ce0b9c-df87-49da-9b97-8b39b2297f71">

**Comment by ojbravo** [comment]
@audayshankar The corrected/updated doc is live in Prod: https://ffiec.cfpb.gov/documentation/api/data-browser/#hmda-data-filters
