### ISSUE TITLE
Missing Files on DEV

### ISSUE THREAD

**Issue by ojbravo** [cfpb/hmda-frontend#1856]
Cypress tests fail on dev because the following  backend files are missing:

**Comment by Michaeldremy** [comment]
Tests to be fixed on DEV:

- MLAR 2020
- Disclosure reports
  - 2019, 2020, 2021
- Graphs | DEV + PROD
   - API `overview` value is returning an empty string, should be a sentence or two with the count of the financial institutions
- HMDA Help - Publications

**Comment by Michaeldremy** [comment]
DEV testing has been fixed for MLAR, Disclosure & Aggregate reports!
