### ISSUE TITLE
Calendar picture not displaying

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#186]
The photo of the annual & quarterly calendar is not showing. 

![image](https://user-images.githubusercontent.com/41752348/73193610-d8b48e00-40f8-11ea-9768-cfe7c46d1c23.png)

![image](https://user-images.githubusercontent.com/41752348/73193627-e36f2300-40f8-11ea-9f31-8ce319839929.png)

**Comment by meissadia** [comment]
<img width="836" alt="Screen Shot 2020-01-27 at 11 45 54 AM" src="https://user-images.githubusercontent.com/2592907/73194711-9ee48700-40fa-11ea-8513-c56291d8d7f6.png">
