### ISSUE TITLE
Page Specific Banner Templates

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-frontend#1860]
#### If the platform will be fully down
Heading: HMDA Filing Platform
Subtitle: The filing platform will be be down for scheduled maintenance between 6pm ET - 8pm ET

#### If there is only a chance of interruption
Heading: HMDA Filing Platform
Subtitle: Users may experience service interruptions on the HMDA filing platform due to scheduled maintenance between 6pm ET - 8pm ET

## Data Browser
Heading: Data Browser
Subtitle: The Data Browser will be down for scheduled maintenance between 6pm ET - 8pm ET

#### If there is only a chance of interruption
Heading: Quarterly Graphs are being updated
Subtitle: There may be some unexpected interruptions as the tool is being updated

#### If the graphs are fully down
Heading: Quarterly Graphs 
Subtitle: The quarterly graphs page will be down for scheduled maintenance between 6pm ET - 8pm ET

## Data Browser Maps
Heading: Data Browser Maps
Subtitle: Maps will be down for scheduled maintenance between 6pm ET - 8pm ET

#### Issue with calculator
Heading: Rate Spread Calculator
Subtitle: The rate spread calculator will be down for scheduled maintenance between 6pm ET - 8pm ET

#### Issue with publication of APOR
Heading: Delay in APOR Publication
Subtitle: The publication of Average Prime Offer Rates (APOR) for the week of [Month Day, Year] is delayed. 

Heading: APOR Tables Available
Subtitle: The publication of Average Prime Offer Rates (APOR) for the week of [Month Day, Year] was delayed. These data are now available on the Rate Spread Calculator [page](https://ffiec.cfpb.gov/tools/rate-spread).

## FFVT
Heading: File Format Verification Tool
Subtitle: The FFVT will be down for scheduled maintenance between 6pm ET - 8pm ET

## Check Digit 
Heading: Check Digit Tool
Subtitle: The Check Digit Tool will be down for scheduled maintenance between 6pm ET - 8pm ET

**Comment by audayshankar** [comment]
Recommend using ET instead of EST, so we don't have to worry about switching between EST and EDT depending on the time of year.

**Comment by audayshankar** [comment]
@Michaeldremy Are there any other scenarios I should add template language for?

**Comment by Michaeldremy** [comment]
@audayshankar This looks great, awesome work! The most likely scenarios for the banners are in the case something is down or may cause interruption to that service which you have covered. Do you think there will be times where we want to give an update on that particular service like Graphs and a new quarter has been released or do you want to keep these updates on the homepage?

**Comment by audayshankar** [comment]
@Michaeldremy Thank you! I think we can keep updates such as a new quarter being added just on the homepage.

**Comment by Michaeldremy** [comment]
Great! I have added these banner templates to the frontend documentation. ✅ 

Thank you for creating these!
