### ISSUE TITLE
Questions hyperlink should open an email message

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#187]
The HMDA Platform homepage https://ffiec.cfpb.gov/filing/2019/ has a hyperlink at the bottom of the page entitled "Questions?". Upon clicking the hyperlink, nothing happens. Seems that the hyperlink should link to an email message to hmdahelp@cfpb.gov. 

![image](https://user-images.githubusercontent.com/41752348/73194426-33021e80-40fa-11ea-83a4-981b983a397b.png)

**Comment by meissadia** [comment]
For me this link does open a new email message in my mail app, addressed to hmdahelp@cfpb.gov.  

This could simply be a matter of end user configuration in terms of how their browser is handles email links.

**Comment by chynnakeys** [comment]
Interesting @meissadia, this doesn't open for me on google chrome at all (on both my machines) & upon selecting it in IE, i receive this message: 
![image](https://user-images.githubusercontent.com/41752348/73200410-b88acc00-4104-11ea-99a0-f90b0f70e9b1.png)

When I select Allow, it takes me to Google Chrome in an empty window.

**Comment by wpears** [comment]
Yeah the `mailto:` link is set up correctly, chynna you may not have gmail configured as a mailto handler in chrome://settings/handlers and/or no default mail client configured on your computer.
