### ISSUE TITLE
Quarterly Graphs Update

### ISSUE THREAD

**Issue by ojbravo** [cfpb/hmda-frontend#1928]
References: https://github.cfpb.gov/HMDA-Operations/hmda-devops/issues/3894

**Comment by kgudel** [comment]
We need a method for changing between different versions of the same graphs. Specifically between three graphs segregated on loan purpose:

1. Home Purchase
2. Refinance
3. All

This could be accomplished by looking at a new field on the API object `loanPurpose` which can either be `all`, `purchase`, or `refinance`
