### ISSUE TITLE
[Synk] Upgrade react-scripts to v5

### ISSUE THREAD

**Issue by Michaeldremy** [cfpb/hmda-frontend#1949]
Upgrading `react-scripts` to `v5` from `v4` requires a lot more changes. 

**Issue:** `react-scripts v5` uses `postcss v8` which requires a migration from `v7` to `v8`. Additionally when upgrading to `v8` you need to update `webpack` to still allow Node to use `polyfills` when building the CSS and JS.

**Error:** `BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.`

**Comment by Michaeldremy** [comment]
Upgrading react-scripts v5 opens up a lot of issues and are not being resolved by the author of the packages as it is no longer being maintained.

Our next step is to migrate over to another build tool, follow #1949 for the progress of that.

Moving ticket to backlog.

**Comment by meissadia** [comment]
> Our next step is to migrate over to another build tool, follow #1949 for the progress of that.

@Michaeldremy #1949 is *this* issue. Looks like #1956 is the ticket for replacing `react-scripts`?

**Comment by Michaeldremy** [comment]
@meissadia That is correct, my mistake! Thanks for pointing that out.

**Comment by Michaeldremy** [comment]
Closing this ticket as we will be moving to Vite after 2023 Annual Filing season. Look at ticket #1956 for more details on this topic.
