### ISSUE TITLE
Discussion on automated front-end testing framework

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-frontend#197]
Short description explaining the high-level reason for the new issue.

## Current behavior

Potentially use https://www.cypress.io/ for front end testing

Discussion Topics: 

- [x] cypress test for 2019 UI filing ( login/ upload/ resolve quality/ resolve macro/ sign)
- [x] cypress test for 2018 UI filing  ( login/ upload/ resolve quality/ resolve macro/ sign)
- [x] cypress test for 2020 quarterly filing  ( login/ upload/ resolve quality/ resolve macro/ sign)
- [x]  automated cypress tests via k8 cron job

**Comment by meissadia** [comment]
It does look like there are a couple of options for uploading files with Cypress:
- [Cypress.Blob](https://docs.cypress.io/api/utilities/blob.html#Syntax)
- [cypress-file-upload npm](https://www.npmjs.com/package/cypress-file-upload)

**Comment by meissadia** [comment]
Cypress environment variables
https://docs.cypress.io/guides/guides/environment-variables.html#Setting
