### ISSUE TITLE
Correction on 2022 MSA/MD Aggregate Report Page For The State Of Texas 

### ISSUE THREAD

**Issue by offoaro** [cfpb/hmda-frontend#2001]
When inputting 2022 on the MSA/ MD Aggregate report page, 2021 shows up for the year even when 2022 data is populated. a correction can just be made to display 2022 instead of 2021.

<img width="832" alt="Screenshot 2023-11-16 170036 (1)" src="https://github.com/cfpb/hmda-frontend/assets/114685069/a0fba6e5-0e0a-4212-91a7-af6e0851e05d">

**Comment by ojbravo** [comment]
From my testing the error is limited to 2022, but occurs for any state/msa/md when the "Application by Income, Race and Ethnicity" Report is selected. All other year/report combinations return the correct year.

The year is populated from the json file that is returned: https://s3.amazonaws.com/cfpb-hmda-public/prod/reports/aggregate/2022/32580/5.json

<img width="853" alt="Screenshot 2023-11-28 at 2 46 04 PM" src="https://github.com/cfpb/hmda-frontend/assets/3650300/8bbbc255-2052-4708-ad05-5ef380be872b">
