### ISSUE TITLE
Make column names more specific

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-frontend#2029]
Add "LAR Count" on the yearly LAR count columns

<img width="668" alt="Screenshot 2023-12-13 at 11 04 36 AM" src="https://github.com/cfpb/hmda-frontend/assets/13244336/f7582da9-544d-463e-887e-739ec45d0c4e">

**Comment by ojbravo** [comment]
@kgudel Is this what you had in mind?
<img width="1107" alt="Screenshot 2024-02-13 at 10 44 39 AM" src="https://github.com/cfpb/hmda-frontend/assets/3650300/71767ab4-2973-4f2b-8784-a0200b0556ce">

**Comment by kgudel** [comment]
Let's update to `Institution Name` and `YYYY LAR Count`

**Comment by ojbravo** [comment]
Two options:

1. LAR title on multiple lines / thinner columns:
<img width="1085" alt="Screenshot 2024-02-14 at 10 32 43 AM" src="https://github.com/cfpb/hmda-frontend/assets/3650300/1c6991ec-31ec-49fe-a971-43f8bc40d885">

2. LAR title on one line / wider columns:
<img width="1148" alt="Screenshot 2024-02-14 at 10 36 01 AM" src="https://github.com/cfpb/hmda-frontend/assets/3650300/a6084d19-55b0-49a3-a01b-5ba435936d5e">

**Comment by meissadia** [comment]
I vote Option 1.  The content of the LAR Count columns is probably the shortest (fewest characters) of them all and seems like, even an extreme case (999,999,999), looks like it should fit without wrapping in the narrow width version.

**Comment by kgudel** [comment]
I think option 1 also looks great!
