### ISSUE TITLE
fix total table in data browser maps 

### ISSUE THREAD

**Issue by zencircle** [cfpb/hmda-frontend#2073]
https://ffiec.cfpb.gov/data-browser/maps/2022?geography=state&variable=actionTaken&value=1&filter=loanType&filtervalue=2&feature=09&mapCenter=-72.72688892809971,41.618725358202305

![image](https://github.com/cfpb/hmda-frontend/assets/25303681/d29356c6-3c1d-493b-810f-99ef492bbf2b)

**Comment by Michaeldremy** [comment]
Closing ticket.

Original design makes it extra clear that there are not supposed to be values in the `Pct` total row.
