### ISSUE TITLE
Issue in Ratespread

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-frontend#21]
The following error appears in the frontend when trying to get a ratespread

<img width="678" alt="ratespread" src="https://user-images.githubusercontent.com/13244336/70639395-465f3600-1bef-11ea-9afb-99390ab4c793.png">

**Comment by meissadia** [comment]
CSP controlled in NGINX config ([source](https://github.com/cfpb/hmda-frontend/blob/1437e65b6bb08f1b515ceacf14b3118034114543/nginx/nginx.conf#L26))

Maybe we add cfpb.gov to the connect-src list?
```
connect-src 'self' https://*.cfbp.gov https://*.mapbox.com https://www.google-analytics.com https://s3.amazonaws.com;
```

**Comment by meissadia** [comment]
This is also an issue on the Documentation page when trying to dynamically render Markdown files stored on Github (ex. any of the FAQs)

**Comment by meissadia** [comment]
Adding `https://raw.githubusercontent.com https://ffiec-api.cfpb.gov https://ffiec.cfpb.gov` found in other frontend UI repos.
