### ISSUE TITLE
Odd elements being displayed in Dashboard UI

### ISSUE THREAD

**Issue by PatrickGoRaft** [cfpb/hmda-frontend#2103]
Short description explaining the high-level reason for the new issue.

## Current behavior

 There seems to be a set of elements expecting values in the HMDA Dashboard that are never provided/populated

## Expected behavior

visiualiation of the data should be consistent. If there's not thing to be shown the UI should pivot in response to this 

## Steps to replicate behavior (include URLs)

1. Navigate to the HMDA-Dashboard UI Summary UI

## Screenshots

![Screen Shot 2024-02-23 at 12 40 59 AM](https://github.com/cfpb/hmda-frontend/assets/44584592/564721e0-fb8d-4e52-a39a-18b7c264ab3e)

**Comment by ojbravo** [comment]
Issue has been corrected in build ```pe-v0.1.3``` 
<img width="824" alt="Screenshot 2024-02-26 at 8 56 33 AM" src="https://github.com/cfpb/hmda-frontend/assets/3650300/c4ca2916-12da-4d6d-b510-2103e4cefb2f">
