### ISSUE TITLE
Akamai mPulse Boomerang Blocked

### ISSUE THREAD

**Issue by ojbravo** [cfpb/hmda-frontend#2126]
This error appeared in the console of the frontend:
<img width="1259" alt="akamai-mpulse-boomerang" src="https://github.com/cfpb/hmda-frontend/assets/3650300/2128b27e-eb31-422d-8bbf-f1a3d3088716">

It is apparently related to Akamai.

From the Akamai website: https://techdocs.akamai.com/mpulse-boomerang/docs/content-security-policy-csp

<img width="844" alt="Screenshot 2024-03-20 at 10 21 12 AM" src="https://github.com/cfpb/hmda-frontend/assets/3650300/bbc966ac-7300-4340-a432-a03446a75097">

**Comment by zencircle** [comment]
This is good to add `Gathering this data helps improve the overall performance of the Akamai CDN, which should improve the performance of all Akamai customer websites.`

**Comment by ojbravo** [comment]
mPulse has been disabled in Prod, so these errors are no longer appearing in the console.
