### ISSUE TITLE
Select Date Range Issue with Quarterly Graphs UI

### ISSUE THREAD

**Issue by jaredb96** [cfpb/hmda-frontend#2153]
I was able to view graphs for ranges that went backwards in time 

<img width="1677" alt="Screenshot 2024-04-10 at 9 47 00 AM" src="https://github.com/cfpb/hmda-frontend/assets/41237993/2a356bdb-9ef7-4230-890b-e9702294684d">
<img width="1677" alt="Screenshot 2024-04-10 at 9 47 00 AM" src="https://github.com/cfpb/hmda-frontend/assets/41237993/06e246da-1c58-494e-a72f-846f88fba539">

**Comment by ojbravo** [comment]
Failing Graphs starting date now limited to quarters prior to end date:
<img width="1018" alt="Screenshot 2024-04-11 at 10 09 05 AM" src="https://github.com/cfpb/hmda-frontend/assets/3650300/d31644e5-5b96-41c7-a00e-50068d7f4587">

**Comment by ojbravo** [comment]
Deployed and passed all tests in build v3.0.6
