### ISSUE TITLE
Upgrade Dashboard-UI to Vite

### ISSUE THREAD

**Issue by ojbravo** [cfpb/hmda-frontend#2217]
Dashboard-UI was built with Create-React-App and needs to be upgraded.

**Comment by Michaeldremy** [comment]
HMDA Dashboard UI repository has been migrated from `Create React App` to `Vite`. There are several other upgrades/updates such as:

- Node has been upgraded to use `v20.8.0`. 
- Dockerfile base image has been upgraded to support Node `v20.8.0` and has been updated to support Vite's way of handling the build.
- Project is now using Yarn V4

**Comment by Michaeldremy** [comment]
Work has been merged into the repo.
