### ISSUE TITLE
Update Graphs to Include explainer about small sample size removal.

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-frontend#2252]
Add the following explainer text below the graphs:

`Note: Data points which would be generated based on fewer than 100 loans are not shown. This may cause gaps in graphs.`

**Comment by Nrbassili** [comment]
Newbie comment (take with a grain of salt)...Should we also add "graphs and tables"? E.g. "This may cause gaps in graphs and tables."

**Comment by kgudel** [comment]
Good addition!

**Comment by Michaeldremy** [comment]
Ticket has been expanded to redesign the `HighCharts` data table by making is expandable.
