### ISSUE TITLE
[Update/Docusaurus] Quarterly Filing Period Graphic

### ISSUE THREAD

**Issue by Michaeldremy** [cfpb/hmda-frontend#2301]
Quarter 3 ending date will need to be updated in the graphic below from November 29th to December 1st. November 29th, 2024 falls on a Friday where as November 29th, 2025 falls on a weekend. Additionally, the `late submissions` date needs to be updated to December 2nd - December 31st.

### Graphic is found under FAQ -> HMDA Data Collection Timelines -> [Quarterly Filing Period Dates](https://ffiec.cfpb.gov/documentation/faq/data-collection-timelines#quarterly-filing-period-dates).

**[Update]** Graphic had the annual removed and the end date for Q3 was changed back to November 29th as documentation needs to stay consistent.

![Image](https://github.com/user-attachments/assets/fccc6d8d-b03a-443a-b0b5-016bc92add80)

### Graphic is also found under the [graphs tool](https://ffiec.cfpb.gov/data-browser/graphs/quarterly/)

![Image](https://github.com/user-attachments/assets/64d5d370-09eb-4c05-a49a-85468590a69c)

**Comment by Nrbassili** [comment]
Updated: https://bcfp365.sharepoint.com/sites/ti-dd/Shared%20Documents/HMDA%20Ops/HMDA/Publication%20and%20Documentation/Filing%20Timeline/Timeline%20Visual.pptx?web=1

**Comment by mmahmood4444** [comment]
Nastasia and I have made the above updates in the PPT slide deck.

**Comment by bofnd** [comment]
I reviewed the 2025 ppt slides and slides are accurate.

**Comment by Michaeldremy** [comment]
Work has been completed for the ticket. Release of the work to production will happen around December 27th.

The [FE Pull Request](https://github.com/cfpb/hmda-frontend/pull/2337) to merge.
The [Docusaurus Pull Request](https://github.com/cfpb/hmda-combined-documentation/pull/79) to merge.
