### ISSUE TITLE
Consistent Colored Headers

### ISSUE THREAD

**Issue by Michaeldremy** [cfpb/hmda-frontend#2303]
There is a mismatch of colored `Header` title text throughout the frontend.

Most of the frontend headers are `black`, there are some that are using the `hmda-blue` color from the [style guide](https://ffiec.cfpb.gov/documentation/api/style-guide/#colors).

Discuss to either use the color `black` or `hmda-blue` across the website.

**Comment by ojbravo** [comment]
Before / After:
![Image](https://github.com/user-attachments/assets/69b78eb6-5dfa-46a5-8180-8e989030846a)

Before / After:
![Image](https://github.com/user-attachments/assets/ffbd92f4-1306-45ec-bc5d-f75f1d3b95e6)

Before / After:
![Image](https://github.com/user-attachments/assets/f45ca5d6-4e3e-4c4f-ac8f-3b094994eeed)
