### ISSUE TITLE
[Docusaurus] Updates / Corrections

### ISSUE THREAD

**Issue by ojbravo** [cfpb/hmda-frontend#2328]
| Page | Subheading | Issue | Correction |
| --- | --- | --- | --- |
| https://ffiec.cfpb.gov/documentation/faq/filing-faq   |  What tools can I use to help prepare my file for submission?  |  FIG link is opening 2022 version  | Routed to current FIG |
|  https://ffiec.cfpb.gov/documentation/faq/data-collection-timelines#annual-filing-period-dates  |  FIG  |   The previous 2018 FIG released before the ruling is also available. (link broken)   | Link fixed |
|  https://ffiec.cfpb.gov/documentation/api/filing/platform  |  HMDA Platform Filing API  |  In order to integrate with the HMDA Platform using Login.gov please contact HMDA Help (hmdahelp@cfpb.gov). - How are we supposed to fix this?  | This is correct. Route request to Eric / Kenneth |
|  https://ffiec.cfpb.gov/documentation/api/file-serving/  |  HMDA File Serving  |  Is Institution Register Summaries link going to the right page?  | Routed to Disclosure Reports >> IRS |
|   Find Resources - HMDA Documentation   |  Code Sheet  |  Is the Code sheet supposed to be updated? This one states 2018  | Kenneth will update |

**Comment by mmahmood4444** [comment]
I am done with my review, and everything looks good except for this one:

![image](https://github.com/user-attachments/assets/1aea9141-6937-4fec-8e8d-008ccd487606)
It does not take me to the Disclosure Reports page rather our filing page. Was that intended or this isn't correct?

**Comment by Nrbassili** [comment]
All looks good to me!

**Comment by ojbravo** [comment]
@mmahmood4444 The link in orange is the one that goes to the Disclosure Report...

<img width="655" alt="Screenshot 2024-11-13 at 4 29 40 PM" src="https://github.com/user-attachments/assets/4d81f16d-a01c-490b-a967-1c6831cdcf93">

**Comment by mmahmood4444** [comment]
> @mmahmood4444 The link in orange is the one that goes to the Disclosure Report...
> 
> <img alt="Screenshot 2024-11-13 at 4 29 40 PM" width="655" src="https://private-user-images.githubusercontent.com/3650300/385981024-4d81f16d-a01c-490b-a967-1c6831cdcf93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTM5MTUsIm5iZiI6MTczMTU1MzYxNSwicGF0aCI6Ii8zNjUwMzAwLzM4NTk4MTAyNC00ZDgxZjE2ZC1hMDFjLTQ5MGItYTk2Ny0xYzY4MzFjZGNmOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMDMwNjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE0ODdhMGRiNmVkYWMzYmFiY2VhYjA0YmY4ZmQzNTNlYjlhMWNmNGU4NmJjNWVjYjlmYzFmMWIxY2QxYTdiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.xueewmJDUDzbaX2-nZTuOqDdBzTqVL79M6d0Lm0VDvI">

Yes, I am aware. When I click on the #3 Institution Registration Summary, it takes me to our filing page not the disclosure page. 
<img width="882" alt="image" src="https://github.com/user-attachments/assets/52d1fc7a-5ad7-4940-9fd9-2302c06ca97d">

**Comment by mmahmood4444** [comment]
Yes, I am aware. When I click on the 3. Institution Registration Summary, it takes me to our filing page not the disclosure page. 

<img width="882" alt="image" src="https://github.com/user-attachments/assets/52d1fc7a-5ad7-4940-9fd9-2302c06ca97d">

**Comment by ojbravo** [comment]
@mmahmood4444 Please make sure you're testing from Dev and not Prod. If you are on Dev, try hitting "Control+Shift+R" (Windows) or "Command+Shift+R" (Mac) to refresh the page with a clean browser cache.

**Comment by bofnd** [comment]
Also, in HMDA Platform API section under Title "Authorization"  the wording following January 1, 2025, needs to change to say 2025 Filing Season instead of 2024 Filing Season. Screenshot provided. 
<img width="1680" alt="Screenshot 2024-11-14 at 10 51 25 AM" src="https://github.com/user-attachments/assets/558d3922-988f-4ae2-9a66-798b67a511a7">

**Comment by mmahmood4444** [comment]
> @mmahmood4444 Please make sure you're testing from Dev and not Prod. If you are on Dev, try hitting "Control+Shift+R" (Windows) or "Command+Shift+R" (Mac) to refresh the page with a clean browser cache.

This works! Thanks Omar
Everything looks good
