### ISSUE TITLE
Improvements to "Institution Not Found" error

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#261]
## Error/Spinner
- Make it a warning (yellow) instead of an error (red)
- Suppress the spinner for not-found Institutions
- Maybe just replace the spinner with the warning message as opposed to saving the "error" in the Redux error store?  That would prevent the error from persisting as well.
<img width="678" alt="Screen Shot 2020-02-21 at 10 59 25 AM" src="https://user-images.githubusercontent.com/2592907/75059513-59696e80-549a-11ea-840d-0fccfccb8191.png">

## Error Persists
- The error message persists across screens (like when viewing a Submission), this is not ideal.
<img width="926" alt="Screen Shot 2020-02-21 at 10 59 45 AM" src="https://user-images.githubusercontent.com/2592907/75060192-98e48a80-549b-11ea-8a3f-b5aeacd71d69.png">

**Comment by meissadia** [comment]
Latest mockups.


## Without Error
<img width="758" alt="Screen Shot 2020-03-05 at 3 55 18 PM" src="https://user-images.githubusercontent.com/2592907/76035265-49bc4200-5efe-11ea-9fbf-c200168922a8.png">

## With Error
<img width="753" alt="Screen Shot 2020-03-05 at 4 00 55 PM" src="https://user-images.githubusercontent.com/2592907/76035310-63f62000-5efe-11ea-8ed9-21ff4598716a.png">

**Comment by wpears** [comment]
Looks great! Thoughts @chynnakeys @MattPerrine?

**Comment by chynnakeys** [comment]
@meissadia the first message "The following institutions" won't appear unless the filer has institutions missing in a selected year, correct?

**Comment by meissadia** [comment]
@chynnakeys That is correct.

**Comment by chynnakeys** [comment]
Great! looks good to me then @wpears @meissadia
