### ISSUE TITLE
Explore differentiating between LAR and TS edits

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#262]
See if we can provide better visual feedback on which edits are specific to the Transmittal Sheet vs LAR related. 

I think this was in reference to a TS edit being shown with a table header of "ULI" when TSs don't have ULIs.   

<img width="894" alt="Screen Shot 2020-02-21 at 11 57 35 AM" src="https://user-images.githubusercontent.com/2592907/75063077-5e7dec00-54a1-11ea-8653-31e2023256f4.png">

**Comment by chynnakeys** [comment]
In addition, list the LEI instead of ULI when there is a transmittal sheet edit (there is no ULI in the transmittal sheet).

**Comment by meissadia** [comment]
> In addition, list the LEI instead of ULI when there is a transmittal sheet edit (there is no ULI in the transmittal sheet).

@chynnakeys From what I can tell, the LEI is already being returned as the identifier for TS edits.

**Comment by meissadia** [comment]
@chynnakeys Can you please confirm that this differentiation (TS vs LAR) is only required for the Syntactical and Validity edits? My understanding is that Quality and Macro apply only to LAR rows.  

I believe the best place to incorporate the new identifying flag is the `/edits` endpoint, which lists all associated edits for a given submission, but for the sake of efficiency I only want to have this flag added where required.

**Comment by chynnakeys** [comment]
This is correct. 
Edits that check both the TS & LAR
S300 
S301 
V600

Edits that check the TS only 
S302
S303
S304
V601
V602
V603 
V604
V605
V606
V607

**Comment by meissadia** [comment]
Hey @chynnakeys,

The required backend change has been made, so I'm back to working on the UI.  

Is there any concern about the case where there will be two columns labeled LEI?  Would this happen for edits other than S303?

<img width="989" alt="ts-after" src="https://user-images.githubusercontent.com/2592907/77115214-8d7d7400-69f3-11ea-9816-f23e2bce7ac1.png">

**Comment by chynnakeys** [comment]
Hey @meissadia i actually don't think both columns need to be there.there only needs to be one LEI column. & I don't believe this is the case for any other edits. Would removing the first column be an option? (also, the L stands for Legal,not Loan :)

**Comment by meissadia** [comment]
@chynnakeys One last sanity check before I PR these changes, can you confirm this shot looks correct?

**S303**: Special case that suppresses the row identifier
**V602**: TS Edit with row identifier as **Legal** Entity Identifier
**V619-3**: LAR Edit with row identifier as Universal Loan Identifier
  
  <br>
<img width="993" alt="Screen Shot 2020-03-20 at 10 12 10 AM" src="https://user-images.githubusercontent.com/2592907/77186283-41d0d600-6a98-11ea-9804-ed4304facf01.png">
