### ISSUE TITLE
Q615-1 clarification request: does not trigger when both values are 0

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-frontend#267]
The Platform does not currently trigger if both TLC and Origination Charges = 0. However, the language in the FIG indicates that it should.

Clarify FIG 2021 language to indicate that when both values are 0 this edit will not trigger.

Moved from [HMDA Platform](https://github.com/cfpb/hmda-platform/issues/3499)

**Comment by chynnakeys** [comment]
This can be closed - this was a FIG language change in 2020 https://github.com/cfpb/hmda-platform/issues/3499 @meissadia
