### ISSUE TITLE
Extract FILING_DEADLINE to Environment Variable

### ISSUE THREAD

**Issue by PatrickGoRaft** [cfpb/hmda-frontend#273]
## Current behavior

Changing the FILING_DEADLINE value to trigger the "filing deadline has  passed"  warning requires a code change to implement.  

## Expected behavior

Changing the filing deadline date value should be configurable via an environment variable.

**Comment by meissadia** [comment]
@wpears For Review

[Commit] [Annual Filing Dates in Config](https://github.com/cfpb/hmda-frontend/pull/136/commits/be44b9b0755290d14e9d2cac60ae7b07b86b0f9f)

## Notes:
- This is implemented with the Quarterly Filing logic to piggy back on the updated deadline calculations. 
- I chose to expand the `config.js` -> `filingQuarters` object, as opposed to creating a separate entry, to avoid having to pass yet another piece of config data down to the dependent components. 

## Changes
- Moves Annual filing deadline dates to `config.json -> filingQuarters`.
- Updates deadline calculations to use new data.
- Removes `dates.js` which previously contained deadline dates.
- Removes unused `#withinAWeekOfDeadline`, which was the last place the `dates.js` deadlines were used.

## Testing Config
- before period is open -> ANNUAL: "04/01 - 05/01"
- period is open -> ANNUAL: "01/01 - 05/01"
- period is closed -> ANNUAL: "01/01 - 03/02"

**Comment by wpears** [comment]
:+1: Works as advertised. We can close this when the quarterly PR is merged to master.
