### ISSUE TITLE
Documentation Updates 

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#289]
Update the Filing FAQs markdown in the documentation section. 
- [x] Explain to users that if they have two separate files (e.g. one for commercial, one for residential) that the files have to be combined into one submission
_If I use separate systems to create my LAR, will uploading more than one at a time be an issue?_
If using two separate systems to create your LAR File, please combine all entries into one file. Uploading a new file will overwrite the first file uploaded.

- [x] Let users know from the outset that HMDA Help only operates via email
_I have a question that's not covered in the FAQ section, what can I do?_
For further questions, please email hmdahelp@cfpb.gov. Note that HMDA Help only operates via email. 

- [x] Ethnicity/race of applicant 1-5 is for the applicant, Ethnicity/race of applicant 2 is not for the co-applicant
_I am receiving formatting errors/edits regarding ethnicity/race of applicants._
Please note that the fields 'Ethnicity of Applicant or Borrower 1-5' and 'Race of Applicant or Borrower 1-5' are for up to 5 ethnicities/races of the first applicant. For any co-applicant ethnicities/races, please enter values in the fields **'Ethnicity of Co-Applicant or Co-Borrower 1-5'** or **'Race of Co-Applicant or Co-Borrower 1-5'.** 

- [x] More information on how to understand your agency code 
_I am unsure of my agency code, where can I find more information?_
Add to the agency code question on https://ffiec.cfpb.gov/documentation/2019/filing-faq/: For additional information, please review page 272 of the 2019 Getting It Right Guide found here: https://www.ffiec.gov/hmda/pdf/2019guide.pdf. This details how the appropriate federal agency is determined. 

- [x] Explain how to find census tract and county code and state code better 
_I am receiving validity edits regarding my county codes & census tracts. Can you explain how these fields are derived?_
Your county code is a 5 digit number that combines state and county codes. Your census tract should be an 11 digit number. Your census tract combines the 2 digit state, 3 digit county, and 6 digit tract code (with no decimal). The FFIEC census tool and FFIEC geocoder can assist in providing the correct state, county and census tract combinations. 
Census Tool: https://www.ffiec.gov/%5C/census/default.aspx
Geocoder: https://geomap.ffiec.gov/FFIECGeocMap/GeocodeMap1.aspx

Should we provide an example? (For example, in the case where the state is Alabama, the 2 digit state code would be 01 and the county (in the state of Alabama) is Baldwin County, the 3 digit county code would be 003. The county code reported would therefore be 01003.  An applicable 6 digit tract code would be 020100. The census tract code would be 01003020100. 

- [x] Guidance with CLTV decimal places: Note the expected behavior in https://github.com/cfpb/hmda-platform/issues/2524
_What decimal precision is the Loan-to-Value ratio rounded to?_ 
The precision of the calculated LTV should be rounded to match the decimal precision of the CLTV.

- [x] What isn’t provided in the national dataset because of privacy concerns (e.g. credit score, application dates) - https://github.com/cfpb/hmda-platform/blob/master/docs/v2/UsingModifiedLar.md
_How can I see a list of fields redacted from the Modified LAR data?_
A list of all fields redacted from the modified LAR data for privacy concerns can be found here: https://github.com/cfpb/hmda-platform/blob/master/docs/v2/UsingModifiedLar.md (we may want to consider moving this to an actual documentation markdown?)

- [x] Where to find info for historic data 2007-2017 
_Where can I find HMDA data prior to 2017?_
Each year thousands of financial institutions report data about mortgages to the public, under the Home Mortgage Disclosure Act (HMDA). We provide the data collected under HMDA from 2007-2017 for download [here](https://www.consumerfinance.gov/data-research/hmda/historic-data/).

**Comment by chynnakeys** [comment]
@MattPerrine can you review these and let me know if you have any changes?

**Comment by MattPerrine** [comment]
@chynnakeys - Let's talk about the following:
- "I am receiving formatting errors/edits regarding ethnicity/race of applicants." 
- "I am unsure of my agency code, where can I find more information?" [I'm not sure we need to quote the Reg.]
- "I am receiving validity edits regarding my county codes & census tracts, how can I fix this?" [I'm not sure the answer addresses the question.]
- "What decimal precision is the Loan-to-Value ratio rounded to?" [Should we provide an example for this one?]
- "Where can I find HMDA data prior to 2017?" [Not sure the first sentence is needed]
