### ISSUE TITLE
Bold Wrong Field in S303 Edit

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#291]
For S303 edits, bold which “Provided, Expected” field wrong. It would make it easier for the user to spot which one is wrong between LEI, Tax ID, or Agency Code

**Comment by meissadia** [comment]
Hey @chynnakeys,

What do you think about the following variations?  I feel like bolding-only might still be too subtle a change to pull the user's eye to the appropriate place. 


### Bolded
<img width="852" alt="bolded" src="https://user-images.githubusercontent.com/2592907/77091709-8728d100-69ce-11ea-9ecf-25c3683a6682.png">

### Highlight whole incorrect field 
<img width="848" alt="all-highlighted2" src="https://user-images.githubusercontent.com/2592907/77093004-04087a80-69d0-11ea-8013-5cbf4e9300f6.png">


### Highlight the incorrect "Provided" value
<img width="846" alt="wrong-highlighted" src="https://user-images.githubusercontent.com/2592907/77092913-e509e880-69cf-11ea-8f8e-3aa08634cbc7.png">

**Comment by chynnakeys** [comment]
@meissadia i like the third option, could you also bold the wrong field?

**Comment by meissadia** [comment]
@chynnakeys The previous image actually does have the `wrong field` bolded 🤷‍♂ but we can bump the font size up a bit to make it more obvious.

<img width="800" alt="Screen Shot 2020-03-19 at 3 39 30 PM" src="https://user-images.githubusercontent.com/2592907/77117727-35953c00-69f8-11ea-96a6-36da234f98b0.png">

**Comment by chynnakeys** [comment]
looks good! @meissadia
