### ISSUE TITLE
Add a print button to the submission page on the platform

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#292]
Give filers the opportunity to print their submission page

**Comment by meissadia** [comment]
@chynnakeys 

Do we always want to present users with the ability to print this page or only show the print option after users have signed?

I'm thinking of making printing an option as part of their Receipt.  
<img width="1028" alt="Screen Shot 2020-03-13 at 1 15 01 AM" src="https://user-images.githubusercontent.com/2592907/76598325-46a9ee80-64c8-11ea-9e07-62ea8696f535.png">

We can also explore creating a pared down print-view that removes the page navigation, colors, etc.  
<img width="1001" alt="Screen Shot 2020-03-13 at 1 17 19 AM" src="https://user-images.githubusercontent.com/2592907/76598482-9a1c3c80-64c8-11ea-8d3a-1665ee9eb456.png">

**Comment by chynnakeys** [comment]
I like being able to print once they signed, since that's what they're looking to print anyways @meissadia
