### ISSUE TITLE
data browser pulls list of institutions from a static file

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-frontend#32]
Short description explaining the high-level reason for the new issue.

## Steps to replicate behavior (include URLs)

1. Data browser is pulling list of insittuions from a static file as opposed to the API

**Comment by meissadia** [comment]
The static institutions files do not exist in `hmda-frontend/data-browser`.

I'm seeing that DB in `dev-default` is making the appropriate calls to the `filers` endpoint to filter Institutions by Geography.

<img width="1089" alt="calling-filers" src="https://user-images.githubusercontent.com/2592907/70731878-b7245200-1cc4-11ea-8956-f273871963c2.png">

**Comment by meissadia** [comment]
Triple checked that API is being used.
