### ISSUE TITLE
Disclosure reports are not showing list of LEIs

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-frontend#33]
Short description explaining the high-level reason for the new issue.

## Steps to replicate behavior (include URLs)

1.

## Screenshots

<img width="1030" alt="Screen Shot 2019-12-12 at 9 25 18 AM" src="https://user-images.githubusercontent.com/44377678/70720211-652dfd00-1cc1-11ea-924b-f0e43737e42b.png">

**Comment by meissadia** [comment]
I think this will be fixed along with Issue #21 once we update the Content Security Policy in the NGINX config.

![content-policy-error](https://user-images.githubusercontent.com/2592907/70734415-70852680-1cc9-11ea-8f31-812f4d0a2508.png)

**Comment by meissadia** [comment]
Fixed by latest deployment. 

![disclosure-leis](https://user-images.githubusercontent.com/2592907/70745102-64589380-1ce0-11ea-83ff-6c8b6cd3ebb7.png)
