### ISSUE TITLE
lar formatting tool does not show up

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-frontend#34]
## Steps to replicate behavior (include URLs)

1.

## Screenshots

Short description explaining the high-level reason for the new issue.
<img width="887" alt="Screen Shot 2019-12-12 at 9 28 01 AM" src="https://user-images.githubusercontent.com/44377678/70720502-e84f5300-1cc1-11ea-8ac7-b6ca8df5330c.png">

**Comment by meissadia** [comment]
Fixed.
