### ISSUE TITLE
Maintenance banner immediately dismissed

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#340]
Banner is automatically being dismissed on page load, at all resolutions.

Banner should only be closable on mobile and should only be dismissed on click of close button.  

![maint-dismissed](https://user-images.githubusercontent.com/2592907/78096854-fbcd1980-7397-11ea-9b7d-c4ba112783f7.gif)

**Comment by wpears** [comment]
I can't repro this locally (modifying the localhost override for the configFetch) so let's this tonight during maintenance to ensure it's still occurring.

**Comment by meissadia** [comment]
I'll keep an eye out. 

Last maintenance window the message seemed to stick correctly on the Filing app but was dismissed on the main page.  I'll make note of which remote configs cause the issue.

**Comment by meissadia** [comment]
Confirmed issue happening again with the behavior mentioned above. 

Attaching remote config.json but github doesn't support json, so it's `.txt`. 


[remote-config.txt](https://github.com/cfpb/hmda-frontend/files/4478380/remote-config.txt)
