### ISSUE TITLE
Docs/FAQ page from databrowser does not show up

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-frontend#36]
Short description explaining the high-level reason for the new issue.

## Steps to replicate behavior (include URLs)

1.

## Screenshots

Docs/FAQ page does not show up

<img width="1680" alt="Screen Shot 2019-12-12 at 9 33 14 AM" src="https://user-images.githubusercontent.com/44377678/70720861-9d820b00-1cc2-11ea-9552-d12650baeb44.png">

**Comment by meissadia** [comment]
@omnipresent07  I think this has the same root cause as Issue #21 

This was an issue for me yesterday but seems to be cleared up this morning.  Was there any update to the Content Security Policy for the `hmda-frontend` in `dev-default`?

**Comment by omnipresent07** [comment]
No update was made. This is still an issue. You have to click FAQ from the data browser page for this to trigger
