### ISSUE TITLE
Run cypress as non root user

### ISSUE THREAD

**Issue by BarakStout** [cfpb/hmda-frontend#381]
After #380 is merged in, we should update `cypress/Dockerfile` to run as non root

**Comment by meissadia** [comment]
Still needed?

Add [something like this](https://github.com/cfpb/hmda-frontend/blob/master/Dockerfile#L25-L29) to the [Cypress Dockerfile](https://github.com/cfpb/hmda-frontend/blob/master/cypress/Dockerfile)?
