### ISSUE TITLE
Increase timeout while waiting for API response

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#404]
There was a one-off error on DB while searching for an LEI, which worked as expected for everyone that tried there-after. 

Investigate what the timeout is currently set to for DB API calls and see if it can be bumped up to avoid issues with uncached queries.

**Comment by meissadia** [comment]
There is no timeout specified on the front-end for DB api calls, nor does seem that the `fetch` api [supports the option](https://stackoverflow.com/a/46946573).

The solution in the above link provides a way to set an upper limit on the time we would wait for a request to complete but not a lower limit.  

We can implement a retry for `getSubsetDetails` which retrieves the aggregation data, since that is where we could encounter a long running query for uncached data.

**Comment by wpears** [comment]
Yeah this is really more of a backend configuration. The frontend will keep a request open indefinitely, but the application server is the thing that's ending the request early on a slow DB response. Of course the reason this behaves this way is so too many slow, simultaneous requests don't end up OOMing the backend, so I don't really know if an increased timeout would be appropriate.

So yeah, perhaps an automatic retry on a specific error code would be the lowest effort & least disruptive change here.
