### ISSUE TITLE
Data Browser - Inconsistent behavior using the vertical scroll in the drop downs

### ISSUE THREAD

**Issue by MattPerrine** [cfpb/hmda-frontend#421]
Inconsistent behavior using the vertical scroll bar:
In IE:
- Sometimes the drop down box disappears when trying to scroll
- The up down arrows also don't seem to move the list

In Chrome:
- Scrolling through the dropdown seems to be fine but when using the arrow keys the blue highlight goes down, but the location does not so all we see are the top entries in the list

**Comment by meissadia** [comment]
Trying out fix proposed [here](https://sung.codes/blog/2019/05/07/scrolling-with-page-up-down-keys-in-react-window/).

**Comment by meissadia** [comment]
Trying out alternate fix: [src](https://github.com/JedWatson/react-select/issues/2976#issuecomment-515022135)

**Comment by meissadia** [comment]
Scrollbar issue might be fixed with react-select version upgrade:
https://github.com/JedWatson/react-select/issues/2816

**Comment by meissadia** [comment]
- Scrollbar not fixed with version bump of `react-select`
- Keyboard nav still not working when testing in IE tab (works for Chrome), even after replacing usage of `findIndex`
