### ISSUE TITLE
Data Browser color mapping inconsistency 

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#481]
Short description explaining the high-level reason for the new issue.

## Current behavior
There are some variables where the legend does not map to the same color displayed on the map. It seems as if the colors aren't refreshing. 

## Screenshots
![image](https://user-images.githubusercontent.com/41752348/83778985-5feeb100-a659-11ea-88b0-75c73137f2b8.png)

**Comment by wpears** [comment]
@chynnakeys I haven't been able to reproduce this locally. What browser were you using when this occurred and can you reliably reproduce it?

**Comment by chynnakeys** [comment]
@wpears @meissadia steps to reproduce: 
In IE, select state, then Action Taken, then 6 - purchased loan. The color of the map should be green. Then select 5 - file closed for incompleteness , the legend changes to coral, but the map is still green.
