### ISSUE TITLE
Jan 1: Open and announce filing season

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#50]
Need to update the config file to enable access to 2019 filing and announce the same on the homepage.

### Homepage
Announcement
The filing period is open. Submissions of 2019 HMDA data will be considered timely if received on or before Monday, March 2, 2020.  
### Filing
Select a year
<u>2019</u> 2018

**Comment by meissadia** [comment]
The attached PR has been updated to reflect the latest modifications to the config structure.
- Added defaultDocsPeriod

**Comment by MattPerrine** [comment]
Updated text for announcement

**Comment by meissadia** [comment]
Updated PR with March 2nd message.
