### ISSUE TITLE
Update 'Documentation' link in site header

### ISSUE THREAD

**Issue by MattPerrine** [cfpb/hmda-frontend#57]
Update the 'Documentation' link in the header to point to the 2019 information; currently it points to the 2018 information.

**Comment by wpears** [comment]
This will be handled by https://github.com/cfpb/hmda-frontend/pull/51. When the defaultPeriod is updated in the env file, the routing will automatically adjust.

**Comment by meissadia** [comment]
I might actually want to create a separate `documentationPeriod` to allow that link to be updated separately. Updating `defaultPeriod` to 2019 would also update the Filing app to default to 2019 but we don't want that to be the case yet.
