### ISSUE TITLE
Remove PR/Push builds on travis-ci.org

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#580]
There are redundant TravisCI builds configured to trigger on PR and `push`. 

travis-ci.com -> build each PR
travis-ci.org -> build each PR
travis-ci.org -> build each branch on push (I think)

TravisCI [recommends all repos use travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/) going forward, so we should disable the extra builds that are happening on travis-ci.org.

![Screen Shot 2020-07-25 at 6 21 24 PM](https://user-images.githubusercontent.com/2592907/88468698-7caea480-cea4-11ea-926e-57aa18be5b21.png)

**Comment by wpears** [comment]
Disabled the redundant tests
