### ISSUE TITLE
Discuss how to navigate between Snapshot, Dynamic, Final, and Ultimate HMDA datasets

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-frontend#631]
Like we have year selectors on the Snapshot and Dynamic publication pages, we could have a "version" selector that allows clicking of Snapshot, Dynamic, Final, or Ultimate which would shift the page and provide links and documentation for the year and version selected.

This would help create a UI flow that would help users understand the differences between the different HMDA versions.

**Comment by meissadia** [comment]
@Kibrael I think this can be closed.  We've demoed the UI captured in PR https://github.com/cfpb/hmda-frontend/pull/661 and the team was on board.

- Screenshot 1: Users can select a year from the main Publications page to see a list of Publications available for that year.
- Screenshot 2: Users can navigate between years on an individual Publications page

We have also discussed that we would need to track the "Last Updated" date for each variation of each Publication, which has not yet been implemented but is on my radar and noted [in the main ticket](https://github.com/cfpb/hmda-frontend/issues/638#issuecomment-694397059)
