### ISSUE TITLE
Publications Change Log

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-frontend#648]
New datasets and products are being released and prior datasets are receiving material updates. These updates, changes, and new products need to be communicated to end users. Creating a section that contains information similar to patch notes would provide us an area to publish metadata regarding updates.

## Current behavior
No updates are supplied to data users regarding changes to datasets or data products.

## Expected behavior
Users are made aware of changes made to datasets and data products so they can assess impacts to their work.

**Comment by meissadia** [comment]
Pending:
- [x] Add logic to only show 3 tables
- [ ] Add keyboard accessibility to filter pills
- [ ] Collect a list of Publications changes for the last year
- [ ] Adjust filter logic to display results that match all keywords?
- [ ] Highlight keywords in results display?
