### ISSUE TITLE
Blank screen on filing application in beta

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-frontend#69]
Intermittent blank screen on filing application

<img width="1560" alt="Screen Shot 2019-12-17 at 9 20 07 PM" src="https://user-images.githubusercontent.com/44377678/71050393-0fb77d00-2113-11ea-8e0e-354d3b9c6af9.png">

## Steps to replicate behavior (include URLs)

1.

**Comment by meissadia** [comment]
Should be fixed by https://github.com/cfpb/hmda-frontend/pull/67
