### ISSUE TITLE
Add link for "For data collected in 2018 incorporating the 2018 HMDA rule"

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#735]
https://s3.amazonaws.com/cfpb-hmda-public/prod/help/2018-hmda-fig-2018-hmda-rule.pdf

**Comment by meissadia** [comment]
Hey @chynnakeys @audayshankar, what do you think of the following options? Also happy to draft more options if neither of these feels right.


## Option 1
<img width="443" alt="Screen Shot 2020-11-05 at 10 08 44 AM" src="https://user-images.githubusercontent.com/2592907/98284779-dcfeb900-1f5e-11eb-81d6-8f74b64a1e33.png">

## Option 2
![Screen Shot 2020-11-05 at 11 56 26 AM](https://user-images.githubusercontent.com/2592907/98284808-e6882100-1f5e-11eb-995d-30292355a179.png)

**Comment by audayshankar** [comment]
I prefer Option 2, since it more clearly shows they both fall under 2018 data collection.
