### ISSUE TITLE
Constantly spinning image on frontend although no network requests have failed

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-frontend#76]
Short description explaining the high-level reason for the new issue.

## Current behavior
<img width="1680" alt="Screen Shot 2019-12-19 at 6 45 23 AM" src="https://user-images.githubusercontent.com/44377678/71171247-4da7c480-222b-11ea-89ac-218e64e901da.png">

## Steps to replicate behavior (include URLs)

1.

**Comment by meissadia** [comment]
Issue was that we were overwriting, instead of appending, the API responses from `/latest` causing us to lose the data for previously fetched institutions that is needed to display the Institution's filing progress.
