### ISSUE TITLE
Include HTTP status code in Filing error message

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-frontend#776]
Short description explaining the high-level reason for the new issue.

## Current behavior
If a 504 error is thrown by the network in middle of the file upload process, the frontend shows "Sorry an error has occurred" and halts the upload process. However, if the users refresh their page after a while, the file upload has actually finished. 

## Expected behavior
This should work as is if the issues with load balancer are resolved. However, in the meantime we might be able to do the below:

If during the file upload process a HTTP 504 is thrown, don't show "Sorry an error has occurred" error to user. Rather just suppress the error and continue. 

## Steps to replicate behavior (include URLs)

1.

**Comment by meissadia** [comment]
Expand the error message to include the HTTP status code so that we don't have to dig for it.

**Comment by meissadia** [comment]
I have not been able to reproduce a `504` error while uploading large files.

- Dev
  - Successfully uploaded 125k (1 GB)
  - Failed to upload 300k (2 GB+) with a `502 - Bad Gateway` after 30mins
- Prod Beta
  - Successfully uploaded 125k (1 GB)

**Comment by meissadia** [comment]
Results from 2/11

- Dev
  - Failed to upload 200k (1.55 GB) with `413 - Request Entity Too Large`
  - Failed to upload 125k (1.08 GB) with `413 - Request Entity Too Large`
- Prod Beta
  - Failed to upload 125k (1.08 GB) with `413 - Request Entity Too Large`
