### ISSUE TITLE
Configure Filing URL based on config file variable

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-frontend#80]
Short description explaining the high-level reason for the new issue.

## Current behavior

There was a hot fix needed for the filing application (https://github.com/cfpb/hmda-frontend/commit/dfb35f3e637d15258f53b290ade90d69066cef52). This hardcoded year should ideally be removed and fetched from the config file.

## Steps to replicate behavior (include URLs)

1.

**Comment by meissadia** [comment]
https://github.com/cfpb/hmda-frontend/blob/master/src/filing/index.js#L54

When visiting the root of the filing app at `/filing/`, the user is redirected to the filing year set via the `defaultPeriod` in the environment config.  

But it sounds like this was not working correctly, so we want to directly set the filing year in the url from the site header?
