### ISSUE TITLE
HMDA Platform error in IE 

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#83]
Short description explaining the high-level reason for the new issue.

## Current behavior
HMDA Platform displays a 405 error in IE 

## Expected behavior
HMDA Platform should operate as normally

## Steps to replicate behavior (include URLs)

1. Visit IE
2. Log in and upload a clean file for 2019 
3. Attempt to sign and submit the file 

## Screenshots
![image](https://user-images.githubusercontent.com/41752348/71284024-c55f1780-232f-11ea-9367-389ae1a5737a.png)

**Comment by wpears** [comment]
This is a backend issue in the beta environment. 405 is "method not allowed", but we're hitting the `/sign` endpoint which should allow both `GET` and `POST`
@omnipresent07
