### ISSUE TITLE
Submission Upload page hangs when no issues are present

### ISSUE THREAD

**Issue by PatrickHSI** [cfpb/hmda-frontend#89]
When uploading a test submission with no macro and no quality edits the UI hangs at `Fetching edits...` with a spinning loading gif

## Current behavior
Uploading a submission with zero errors causes the page not to update.

## Expected behavior

Users should be taken to the sign submission page

## Steps to replicate behavior (include URLs)

1. Upload a submission no quality or macro edits
2. Refreshing the page takes you back to the same view
3. Clicking on the (5) Submission step icon allows to go to the signing page.

## Test File

 you can test with the newmanBank_no_M_no_Q_2019.txt  found in /hmda-platform/newman/dev/hmda-filing/test_no_m_no_q/newmanBank_no_M_no_Q_2019.txt

Add the newman LEI to your test account or update the submission file  information to .a LEI/ULI /Tax ID/Bank already associated with your test account. 

## Screenshots

<img width="1120" alt="Screen Shot 2019-12-22 at 9 39 02 AM" src="https://user-images.githubusercontent.com/44584592/71323296-87810100-249f-11ea-8515-054755f73c62.png">
<img width="1565" alt="Screen Shot 2019-12-22 at 9 44 58 AM" src="https://user-images.githubusercontent.com/44584592/71323324-cb740600-249f-11ea-9062-833b2347af5f.png">

**Comment by meissadia** [comment]
Tested in `dev-default` and `prod-beta` with the Newman bank and Bank 0.  Unable to recreate this issue.
