### ISSUE TITLE
Remove Panel Documentation from Dynamic Page

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-frontend#916]
Short description explaining the high-level reason for the new issue.

## Current behavior
![image](https://user-images.githubusercontent.com/58990254/115049494-c9aa2f00-9ea8-11eb-84f8-4877c9fdf90c.png)

There isn't a dynamic panel dataset, so the file specs on the right side ("Public Panel Schema, Public Panel Values and Definition") don't need to be linked on this page. They only need to be linked on the Snapshot page.

**Comment by meissadia** [comment]
Hey @audayshankar, links are removed.

Please take a look at the following ideas.  We can provide a stronger connection between the Schema and Field Definitions documents, I'm just not sure if putting them on a single line is too streamlined / less discernible.

| as-is | reworded | merged |
|--|--|--|
|<img width="950" alt="as-is" src="https://user-images.githubusercontent.com/2592907/115086162-fb32f280-9ec8-11eb-907a-7213b9cd20ca.png">|<img width="907" alt="reworded" src="https://user-images.githubusercontent.com/2592907/115086181-01c16a00-9ec9-11eb-9d93-0f6f092bdfe5.png">|
|merged |
<img width="922" alt="merged" src="https://user-images.githubusercontent.com/2592907/115086196-06861e00-9ec9-11eb-917c-2e4ddce0b4a0.png">|

**Comment by audayshankar** [comment]
I like the reworded option the best. Maybe changing the order of the bullets to have the LAR field definitions second and the TS schema third could be a compromise to the merged option because then the two LAR documents would be grouped together.
