### ISSUE TITLE
Upgrade Node and Nginx

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#942]
## Current versions:
```
Base Image           Vulnerabilities  Severity
nginx:1.19.2-alpine  35               2 critical, 15 high, 14 medium, 4 low
node:14.9-alpine     27               2 critical, 13 high, 9 medium, 3 low
```

## Available upgrades:
|product| Maintenance level |  image tag | Status | Scan |
|--|--|--|--|--|
|nginx|Stable | 1.20.1-alpine| 0 Vulnerabilities |  <img width="694" alt="scan-nginx-1 20 1-apline" src="https://user-images.githubusercontent.com/2592907/131728858-b1e460bd-17fa-47d5-87a1-2f2a49f63221.png"> |
|node|Active LTS | 14.17.6-apline3.11|  0 Vulnerabilities |  <img width="692" alt="scan-node-14 17 6-alpine3 11" src="https://user-images.githubusercontent.com/2592907/131728243-53d2058e-4472-4c17-b03d-af434e406749.png">|

After updating `Dockerfile` with the updated base images:
<img width="694" alt="scan-frontend-after-upgrades" src="https://user-images.githubusercontent.com/2592907/131734532-07e012b9-7a1c-4c12-8657-c8273a6d4730.png">

## Pending
Note: Also upgrade frontend dependency @testing-library/cypress to 8.0.0 (incompatible with node 14.9.0)

**Comment by RoachMJ** [comment]
As of now now cve are present on the image: nginx alpine has released 3.13, 
https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile

**Comment by meissadia** [comment]
- [x] Vulnerability scanning of these images came back clear. 
- [ ] Need to perform integration testing to verify functionality though NGINX
  - [ ]  Get Platform running in Dev
- [ ] Tack on dependency updates once initial integration testing is successful

**Comment by meissadia** [comment]
Testing of updated images reveals issues logging in to the Frontend via Keycloak.  At first, these issues seemed isolated to Chrome browser and were not occurring when logging in via Safari.  After additional testing, the issue seems to be more pervasive on Safari than on Chrome. 

Chrome
- Visit /filing
- Click login
- Enter credential on Keycloak screen
- Observe: Instead of being redirected to the Filers status page, user is kicked back to the /filing landing page
- Click login again and user is signed-in to the Filing app and appropriately directed to the Filers status page
- Upon reload of the page, user is again sent to the /filing landing page instead of being recognized as already logged in
- Clicking login at this point may allow the user to access the Filers status page, or user may once again end up on the /filing landing page.  Multiple attempts at clicking Login may or may not eventually enable the user to proceed.  

Safari
- Visit /filing
- Click login
- Enter credential on Keycloak screen
- User is logged in as expected
- Upon page reload, user is sent to /filing landing page instead of being recognized as logged-in
- Clicking Login again (multiple times) may or may not sign the user in
- Using dev tools to clear the browser cache, then repeating the login flow allowed the user to once again access the Filing app, but on the next visit the inability to login was observed.

https://user-images.githubusercontent.com/2592907/132047941-41a536bd-12d9-4a9c-a9ae-9a1c76d21aeb.mov



Cypress (Chrome)
- Programmatically logs user in via the API
- Upon navigating the /filing landing page, user presented with the LOGIN button, whereas the test expects to be ushered into the filing application.
- Since Cypress cannot find the 'upload a file' region of the page, the test times out and fails
