### ISSUE TITLE
Maps Language Update

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#971]
Change loans to applications in report ![image](https://user-images.githubusercontent.com/41752348/118672237-16de3100-b7c6-11eb-9ba1-06d93a51a834.png)

In Internet Explorer, the icons are zoomed in. I was not able to replicate this in Edge or Chrome. ![image](https://user-images.githubusercontent.com/41752348/118672744-79cfc800-b7c6-11eb-8b65-1c0cc70d78bb.png)

The Maps FAQ in HMDA4 is not working currently

**Comment by meissadia** [comment]
Language updated in #966

**Comment by meissadia** [comment]
IE issue: does not support CSS max/min.  Replaced dynamic font sizing with static.

**Comment by meissadia** [comment]
Maps FAQ not copied to all Documentation directories (/2019, /2018, /2020)

**Comment by meissadia** [comment]
Maps FAQ images not rendering on FFIEC, need to replace relative image links in the markdown with direct github raw links.
