### ISSUE TITLE
Error on print view of rate spread

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-frontend#98]
Short description explaining the high-level reason for the new issue.

## Current behavior
![Image Pasted at 2019-12-31 16-33](https://user-images.githubusercontent.com/44377678/71635274-135a0200-2bf1-11ea-9d61-d8aee1c796b2.png)

## Expected behavior
![Image Pasted at 2019-12-31 16-32](https://user-images.githubusercontent.com/44377678/71635275-1523c580-2bf1-11ea-877e-93068f5e095a.png)

## Steps to replicate behavior (include URLs)

1.

**Comment by meissadia** [comment]
Poking around, this happens when trying to print any of the Tool pages.

**Comment by chynnakeys** [comment]
Users are finding that the print view is still a bit off. It's missing the radio buttons 
![image](https://user-images.githubusercontent.com/41752348/71837855-674b6780-3085-11ea-851f-c08ce37ee3de.png)

Looks like this section is missing: 
![image](https://user-images.githubusercontent.com/41752348/71837906-84803600-3085-11ea-8504-80f7a9bde392.png)
